/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public class _GAppLaunchContextClass {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GAppLaunchContextClass(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GAppLaunchContextClass obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fridacoreJNI.delete__GAppLaunchContextClass(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setParent_class(_GObjectClass value) {
    fridacoreJNI._GAppLaunchContextClass_parent_class_set(swigCPtr, this, _GObjectClass.getCPtr(value), value);
  }

  public _GObjectClass getParent_class() {
    long cPtr = fridacoreJNI._GAppLaunchContextClass_parent_class_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GObjectClass(cPtr, false);
  }

  public void setGet_display(SWIGTYPE_p_f_p__GAppLaunchContext_p__GAppInfo_p__GList__p_char value) {
    fridacoreJNI._GAppLaunchContextClass_get_display_set(swigCPtr, this, SWIGTYPE_p_f_p__GAppLaunchContext_p__GAppInfo_p__GList__p_char.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GAppLaunchContext_p__GAppInfo_p__GList__p_char getGet_display() {
    long cPtr = fridacoreJNI._GAppLaunchContextClass_get_display_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GAppLaunchContext_p__GAppInfo_p__GList__p_char(cPtr, false);
  }

  public void setGet_startup_notify_id(SWIGTYPE_p_f_p__GAppLaunchContext_p__GAppInfo_p__GList__p_char value) {
    fridacoreJNI._GAppLaunchContextClass_get_startup_notify_id_set(swigCPtr, this, SWIGTYPE_p_f_p__GAppLaunchContext_p__GAppInfo_p__GList__p_char.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GAppLaunchContext_p__GAppInfo_p__GList__p_char getGet_startup_notify_id() {
    long cPtr = fridacoreJNI._GAppLaunchContextClass_get_startup_notify_id_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GAppLaunchContext_p__GAppInfo_p__GList__p_char(cPtr, false);
  }

  public void setLaunch_failed(SWIGTYPE_p_f_p__GAppLaunchContext_p_q_const__char__void value) {
    fridacoreJNI._GAppLaunchContextClass_launch_failed_set(swigCPtr, this, SWIGTYPE_p_f_p__GAppLaunchContext_p_q_const__char__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GAppLaunchContext_p_q_const__char__void getLaunch_failed() {
    long cPtr = fridacoreJNI._GAppLaunchContextClass_launch_failed_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GAppLaunchContext_p_q_const__char__void(cPtr, false);
  }

  public void setLaunched(SWIGTYPE_p_f_p__GAppLaunchContext_p__GAppInfo_p__GVariant__void value) {
    fridacoreJNI._GAppLaunchContextClass_launched_set(swigCPtr, this, SWIGTYPE_p_f_p__GAppLaunchContext_p__GAppInfo_p__GVariant__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GAppLaunchContext_p__GAppInfo_p__GVariant__void getLaunched() {
    long cPtr = fridacoreJNI._GAppLaunchContextClass_launched_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GAppLaunchContext_p__GAppInfo_p__GVariant__void(cPtr, false);
  }

  public void set_g_reserved1(SWIGTYPE_p_f_void__void value) {
    fridacoreJNI._GAppLaunchContextClass__g_reserved1_set(swigCPtr, this, SWIGTYPE_p_f_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_void__void get_g_reserved1() {
    long cPtr = fridacoreJNI._GAppLaunchContextClass__g_reserved1_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_void__void(cPtr, false);
  }

  public void set_g_reserved2(SWIGTYPE_p_f_void__void value) {
    fridacoreJNI._GAppLaunchContextClass__g_reserved2_set(swigCPtr, this, SWIGTYPE_p_f_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_void__void get_g_reserved2() {
    long cPtr = fridacoreJNI._GAppLaunchContextClass__g_reserved2_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_void__void(cPtr, false);
  }

  public void set_g_reserved3(SWIGTYPE_p_f_void__void value) {
    fridacoreJNI._GAppLaunchContextClass__g_reserved3_set(swigCPtr, this, SWIGTYPE_p_f_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_void__void get_g_reserved3() {
    long cPtr = fridacoreJNI._GAppLaunchContextClass__g_reserved3_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_void__void(cPtr, false);
  }

  public void set_g_reserved4(SWIGTYPE_p_f_void__void value) {
    fridacoreJNI._GAppLaunchContextClass__g_reserved4_set(swigCPtr, this, SWIGTYPE_p_f_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_void__void get_g_reserved4() {
    long cPtr = fridacoreJNI._GAppLaunchContextClass__g_reserved4_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_void__void(cPtr, false);
  }

  public _GAppLaunchContextClass() {
    this(fridacoreJNI.new__GAppLaunchContextClass(), true);
  }

}
