/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public class _GArray {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fridacoreJNI.delete__GArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setData(String value) {
    fridacoreJNI._GArray_data_set(swigCPtr, this, value);
  }

  public String getData() {
    return fridacoreJNI._GArray_data_get(swigCPtr, this);
  }

  public void setLen(long value) {
    fridacoreJNI._GArray_len_set(swigCPtr, this, value);
  }

  public long getLen() {
    return fridacoreJNI._GArray_len_get(swigCPtr, this);
  }

  public _GArray() {
    this(fridacoreJNI.new__GArray(), true);
  }

}
