/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public class _GClosure {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GClosure(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GClosure obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fridacoreJNI.delete__GClosure(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRef_count(long value) {
    fridacoreJNI._GClosure_ref_count_set(swigCPtr, this, value);
  }

  public long getRef_count() {
    return fridacoreJNI._GClosure_ref_count_get(swigCPtr, this);
  }

  public void setMeta_marshal_nouse(long value) {
    fridacoreJNI._GClosure_meta_marshal_nouse_set(swigCPtr, this, value);
  }

  public long getMeta_marshal_nouse() {
    return fridacoreJNI._GClosure_meta_marshal_nouse_get(swigCPtr, this);
  }

  public void setN_guards(long value) {
    fridacoreJNI._GClosure_n_guards_set(swigCPtr, this, value);
  }

  public long getN_guards() {
    return fridacoreJNI._GClosure_n_guards_get(swigCPtr, this);
  }

  public void setN_fnotifiers(long value) {
    fridacoreJNI._GClosure_n_fnotifiers_set(swigCPtr, this, value);
  }

  public long getN_fnotifiers() {
    return fridacoreJNI._GClosure_n_fnotifiers_get(swigCPtr, this);
  }

  public void setN_inotifiers(long value) {
    fridacoreJNI._GClosure_n_inotifiers_set(swigCPtr, this, value);
  }

  public long getN_inotifiers() {
    return fridacoreJNI._GClosure_n_inotifiers_get(swigCPtr, this);
  }

  public void setIn_inotify(long value) {
    fridacoreJNI._GClosure_in_inotify_set(swigCPtr, this, value);
  }

  public long getIn_inotify() {
    return fridacoreJNI._GClosure_in_inotify_get(swigCPtr, this);
  }

  public void setFloating(long value) {
    fridacoreJNI._GClosure_floating_set(swigCPtr, this, value);
  }

  public long getFloating() {
    return fridacoreJNI._GClosure_floating_get(swigCPtr, this);
  }

  public void setDerivative_flag(long value) {
    fridacoreJNI._GClosure_derivative_flag_set(swigCPtr, this, value);
  }

  public long getDerivative_flag() {
    return fridacoreJNI._GClosure_derivative_flag_get(swigCPtr, this);
  }

  public void setIn_marshal(long value) {
    fridacoreJNI._GClosure_in_marshal_set(swigCPtr, this, value);
  }

  public long getIn_marshal() {
    return fridacoreJNI._GClosure_in_marshal_get(swigCPtr, this);
  }

  public void setIs_invalid(long value) {
    fridacoreJNI._GClosure_is_invalid_set(swigCPtr, this, value);
  }

  public long getIs_invalid() {
    return fridacoreJNI._GClosure_is_invalid_get(swigCPtr, this);
  }

  public void setMarshal(SWIGTYPE_p_f_p__GClosure_p__GValue_unsigned_int_p_q_const___GValue_p_void_p_void__void value) {
    fridacoreJNI._GClosure_marshal_set(swigCPtr, this, SWIGTYPE_p_f_p__GClosure_p__GValue_unsigned_int_p_q_const___GValue_p_void_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GClosure_p__GValue_unsigned_int_p_q_const___GValue_p_void_p_void__void getMarshal() {
    long cPtr = fridacoreJNI._GClosure_marshal_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GClosure_p__GValue_unsigned_int_p_q_const___GValue_p_void_p_void__void(cPtr, false);
  }

  public void setData(SWIGTYPE_p_void value) {
    fridacoreJNI._GClosure_data_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getData() {
    long cPtr = fridacoreJNI._GClosure_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setNotifiers(_GClosureNotifyData value) {
    fridacoreJNI._GClosure_notifiers_set(swigCPtr, this, _GClosureNotifyData.getCPtr(value), value);
  }

  public _GClosureNotifyData getNotifiers() {
    long cPtr = fridacoreJNI._GClosure_notifiers_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GClosureNotifyData(cPtr, false);
  }

  public _GClosure() {
    this(fridacoreJNI.new__GClosure(), true);
  }

}
