/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public class _GDBusInterfaceInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GDBusInterfaceInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GDBusInterfaceInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fridacoreJNI.delete__GDBusInterfaceInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRef_count(int value) {
    fridacoreJNI._GDBusInterfaceInfo_ref_count_set(swigCPtr, this, value);
  }

  public int getRef_count() {
    return fridacoreJNI._GDBusInterfaceInfo_ref_count_get(swigCPtr, this);
  }

  public void setName(String value) {
    fridacoreJNI._GDBusInterfaceInfo_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return fridacoreJNI._GDBusInterfaceInfo_name_get(swigCPtr, this);
  }

  public void setMethods(SWIGTYPE_p_p__GDBusMethodInfo value) {
    fridacoreJNI._GDBusInterfaceInfo_methods_set(swigCPtr, this, SWIGTYPE_p_p__GDBusMethodInfo.getCPtr(value));
  }

  public SWIGTYPE_p_p__GDBusMethodInfo getMethods() {
    long cPtr = fridacoreJNI._GDBusInterfaceInfo_methods_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p__GDBusMethodInfo(cPtr, false);
  }

  public void setSignals(SWIGTYPE_p_p__GDBusSignalInfo value) {
    fridacoreJNI._GDBusInterfaceInfo_signals_set(swigCPtr, this, SWIGTYPE_p_p__GDBusSignalInfo.getCPtr(value));
  }

  public SWIGTYPE_p_p__GDBusSignalInfo getSignals() {
    long cPtr = fridacoreJNI._GDBusInterfaceInfo_signals_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p__GDBusSignalInfo(cPtr, false);
  }

  public void setProperties(SWIGTYPE_p_p__GDBusPropertyInfo value) {
    fridacoreJNI._GDBusInterfaceInfo_properties_set(swigCPtr, this, SWIGTYPE_p_p__GDBusPropertyInfo.getCPtr(value));
  }

  public SWIGTYPE_p_p__GDBusPropertyInfo getProperties() {
    long cPtr = fridacoreJNI._GDBusInterfaceInfo_properties_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p__GDBusPropertyInfo(cPtr, false);
  }

  public void setAnnotations(SWIGTYPE_p_p__GDBusAnnotationInfo value) {
    fridacoreJNI._GDBusInterfaceInfo_annotations_set(swigCPtr, this, SWIGTYPE_p_p__GDBusAnnotationInfo.getCPtr(value));
  }

  public SWIGTYPE_p_p__GDBusAnnotationInfo getAnnotations() {
    long cPtr = fridacoreJNI._GDBusInterfaceInfo_annotations_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p__GDBusAnnotationInfo(cPtr, false);
  }

  public _GDBusInterfaceInfo() {
    this(fridacoreJNI.new__GDBusInterfaceInfo(), true);
  }

}
