/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public class _GDBusNodeInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GDBusNodeInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GDBusNodeInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fridacoreJNI.delete__GDBusNodeInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRef_count(int value) {
    fridacoreJNI._GDBusNodeInfo_ref_count_set(swigCPtr, this, value);
  }

  public int getRef_count() {
    return fridacoreJNI._GDBusNodeInfo_ref_count_get(swigCPtr, this);
  }

  public void setPath(String value) {
    fridacoreJNI._GDBusNodeInfo_path_set(swigCPtr, this, value);
  }

  public String getPath() {
    return fridacoreJNI._GDBusNodeInfo_path_get(swigCPtr, this);
  }

  public void setInterfaces(SWIGTYPE_p_p__GDBusInterfaceInfo value) {
    fridacoreJNI._GDBusNodeInfo_interfaces_set(swigCPtr, this, SWIGTYPE_p_p__GDBusInterfaceInfo.getCPtr(value));
  }

  public SWIGTYPE_p_p__GDBusInterfaceInfo getInterfaces() {
    long cPtr = fridacoreJNI._GDBusNodeInfo_interfaces_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p__GDBusInterfaceInfo(cPtr, false);
  }

  public void setNodes(SWIGTYPE_p_p__GDBusNodeInfo value) {
    fridacoreJNI._GDBusNodeInfo_nodes_set(swigCPtr, this, SWIGTYPE_p_p__GDBusNodeInfo.getCPtr(value));
  }

  public SWIGTYPE_p_p__GDBusNodeInfo getNodes() {
    long cPtr = fridacoreJNI._GDBusNodeInfo_nodes_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p__GDBusNodeInfo(cPtr, false);
  }

  public void setAnnotations(SWIGTYPE_p_p__GDBusAnnotationInfo value) {
    fridacoreJNI._GDBusNodeInfo_annotations_set(swigCPtr, this, SWIGTYPE_p_p__GDBusAnnotationInfo.getCPtr(value));
  }

  public SWIGTYPE_p_p__GDBusAnnotationInfo getAnnotations() {
    long cPtr = fridacoreJNI._GDBusNodeInfo_annotations_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p__GDBusAnnotationInfo(cPtr, false);
  }

  public _GDBusNodeInfo() {
    this(fridacoreJNI.new__GDBusNodeInfo(), true);
  }

}
