/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public class _GDBusInterfaceIface {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GDBusInterfaceIface(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GDBusInterfaceIface obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fridacoreJNI.delete__GDBusInterfaceIface(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setParent_iface(_GTypeInterface value) {
    fridacoreJNI._GDBusInterfaceIface_parent_iface_set(swigCPtr, this, _GTypeInterface.getCPtr(value), value);
  }

  public _GTypeInterface getParent_iface() {
    long cPtr = fridacoreJNI._GDBusInterfaceIface_parent_iface_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GTypeInterface(cPtr, false);
  }

  public void setGet_info(SWIGTYPE_p_f_p_GDBusInterface__p__GDBusInterfaceInfo value) {
    fridacoreJNI._GDBusInterfaceIface_get_info_set(swigCPtr, this, SWIGTYPE_p_f_p_GDBusInterface__p__GDBusInterfaceInfo.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_GDBusInterface__p__GDBusInterfaceInfo getGet_info() {
    long cPtr = fridacoreJNI._GDBusInterfaceIface_get_info_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_GDBusInterface__p__GDBusInterfaceInfo(cPtr, false);
  }

  public void setGet_object(SWIGTYPE_p_f_p__GDBusInterface__p__GDBusObject value) {
    fridacoreJNI._GDBusInterfaceIface_get_object_set(swigCPtr, this, SWIGTYPE_p_f_p__GDBusInterface__p__GDBusObject.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GDBusInterface__p__GDBusObject getGet_object() {
    long cPtr = fridacoreJNI._GDBusInterfaceIface_get_object_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GDBusInterface__p__GDBusObject(cPtr, false);
  }

  public void setSet_object(SWIGTYPE_p_f_p__GDBusInterface_p__GDBusObject__void value) {
    fridacoreJNI._GDBusInterfaceIface_set_object_set(swigCPtr, this, SWIGTYPE_p_f_p__GDBusInterface_p__GDBusObject__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GDBusInterface_p__GDBusObject__void getSet_object() {
    long cPtr = fridacoreJNI._GDBusInterfaceIface_set_object_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GDBusInterface_p__GDBusObject__void(cPtr, false);
  }

  public void setDup_object(SWIGTYPE_p_f_p__GDBusInterface__p__GDBusObject value) {
    fridacoreJNI._GDBusInterfaceIface_dup_object_set(swigCPtr, this, SWIGTYPE_p_f_p__GDBusInterface__p__GDBusObject.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GDBusInterface__p__GDBusObject getDup_object() {
    long cPtr = fridacoreJNI._GDBusInterfaceIface_dup_object_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GDBusInterface__p__GDBusObject(cPtr, false);
  }

  public _GDBusInterfaceIface() {
    this(fridacoreJNI.new__GDBusInterfaceIface(), true);
  }

}
