/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public class _GDBusObjectSkeletonClass {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GDBusObjectSkeletonClass(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GDBusObjectSkeletonClass obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fridacoreJNI.delete__GDBusObjectSkeletonClass(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setParent_class(_GObjectClass value) {
    fridacoreJNI._GDBusObjectSkeletonClass_parent_class_set(swigCPtr, this, _GObjectClass.getCPtr(value), value);
  }

  public _GObjectClass getParent_class() {
    long cPtr = fridacoreJNI._GDBusObjectSkeletonClass_parent_class_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GObjectClass(cPtr, false);
  }

  public void setAuthorize_method(SWIGTYPE_p_f_p__GDBusObjectSkeleton_p__GDBusInterfaceSkeleton_p__GDBusMethodInvocation__int value) {
    fridacoreJNI._GDBusObjectSkeletonClass_authorize_method_set(swigCPtr, this, SWIGTYPE_p_f_p__GDBusObjectSkeleton_p__GDBusInterfaceSkeleton_p__GDBusMethodInvocation__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GDBusObjectSkeleton_p__GDBusInterfaceSkeleton_p__GDBusMethodInvocation__int getAuthorize_method() {
    long cPtr = fridacoreJNI._GDBusObjectSkeletonClass_authorize_method_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GDBusObjectSkeleton_p__GDBusInterfaceSkeleton_p__GDBusMethodInvocation__int(cPtr, false);
  }

  public void setPadding(SWIGTYPE_p_p_void value) {
    fridacoreJNI._GDBusObjectSkeletonClass_padding_set(swigCPtr, this, SWIGTYPE_p_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_p_void getPadding() {
    long cPtr = fridacoreJNI._GDBusObjectSkeletonClass_padding_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_void(cPtr, false);
  }

  public _GDBusObjectSkeletonClass() {
    this(fridacoreJNI.new__GDBusObjectSkeletonClass(), true);
  }

}
