/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public class _GDBusInterfaceSkeletonClass {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GDBusInterfaceSkeletonClass(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GDBusInterfaceSkeletonClass obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fridacoreJNI.delete__GDBusInterfaceSkeletonClass(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setParent_class(_GObjectClass value) {
    fridacoreJNI._GDBusInterfaceSkeletonClass_parent_class_set(swigCPtr, this, _GObjectClass.getCPtr(value), value);
  }

  public _GObjectClass getParent_class() {
    long cPtr = fridacoreJNI._GDBusInterfaceSkeletonClass_parent_class_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GObjectClass(cPtr, false);
  }

  public void setGet_info(SWIGTYPE_p_f_p_GDBusInterfaceSkeleton__p__GDBusInterfaceInfo value) {
    fridacoreJNI._GDBusInterfaceSkeletonClass_get_info_set(swigCPtr, this, SWIGTYPE_p_f_p_GDBusInterfaceSkeleton__p__GDBusInterfaceInfo.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_GDBusInterfaceSkeleton__p__GDBusInterfaceInfo getGet_info() {
    long cPtr = fridacoreJNI._GDBusInterfaceSkeletonClass_get_info_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_GDBusInterfaceSkeleton__p__GDBusInterfaceInfo(cPtr, false);
  }

  public void setGet_vtable(SWIGTYPE_p_f_p_GDBusInterfaceSkeleton__p__GDBusInterfaceVTable value) {
    fridacoreJNI._GDBusInterfaceSkeletonClass_get_vtable_set(swigCPtr, this, SWIGTYPE_p_f_p_GDBusInterfaceSkeleton__p__GDBusInterfaceVTable.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_GDBusInterfaceSkeleton__p__GDBusInterfaceVTable getGet_vtable() {
    long cPtr = fridacoreJNI._GDBusInterfaceSkeletonClass_get_vtable_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_GDBusInterfaceSkeleton__p__GDBusInterfaceVTable(cPtr, false);
  }

  public void setGet_properties(SWIGTYPE_p_f_p__GDBusInterfaceSkeleton__p__GVariant value) {
    fridacoreJNI._GDBusInterfaceSkeletonClass_get_properties_set(swigCPtr, this, SWIGTYPE_p_f_p__GDBusInterfaceSkeleton__p__GVariant.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GDBusInterfaceSkeleton__p__GVariant getGet_properties() {
    long cPtr = fridacoreJNI._GDBusInterfaceSkeletonClass_get_properties_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GDBusInterfaceSkeleton__p__GVariant(cPtr, false);
  }

  public void setFlush(SWIGTYPE_p_f_p__GDBusInterfaceSkeleton__void value) {
    fridacoreJNI._GDBusInterfaceSkeletonClass_flush_set(swigCPtr, this, SWIGTYPE_p_f_p__GDBusInterfaceSkeleton__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GDBusInterfaceSkeleton__void getFlush() {
    long cPtr = fridacoreJNI._GDBusInterfaceSkeletonClass_flush_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GDBusInterfaceSkeleton__void(cPtr, false);
  }

  public void setVfunc_padding(SWIGTYPE_p_p_void value) {
    fridacoreJNI._GDBusInterfaceSkeletonClass_vfunc_padding_set(swigCPtr, this, SWIGTYPE_p_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_p_void getVfunc_padding() {
    long cPtr = fridacoreJNI._GDBusInterfaceSkeletonClass_vfunc_padding_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_void(cPtr, false);
  }

  public void setG_authorize_method(SWIGTYPE_p_f_p__GDBusInterfaceSkeleton_p__GDBusMethodInvocation__int value) {
    fridacoreJNI._GDBusInterfaceSkeletonClass_g_authorize_method_set(swigCPtr, this, SWIGTYPE_p_f_p__GDBusInterfaceSkeleton_p__GDBusMethodInvocation__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GDBusInterfaceSkeleton_p__GDBusMethodInvocation__int getG_authorize_method() {
    long cPtr = fridacoreJNI._GDBusInterfaceSkeletonClass_g_authorize_method_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GDBusInterfaceSkeleton_p__GDBusMethodInvocation__int(cPtr, false);
  }

  public void setSignal_padding(SWIGTYPE_p_p_void value) {
    fridacoreJNI._GDBusInterfaceSkeletonClass_signal_padding_set(swigCPtr, this, SWIGTYPE_p_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_p_void getSignal_padding() {
    long cPtr = fridacoreJNI._GDBusInterfaceSkeletonClass_signal_padding_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_void(cPtr, false);
  }

  public _GDBusInterfaceSkeletonClass() {
    this(fridacoreJNI.new__GDBusInterfaceSkeletonClass(), true);
  }

}
