/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public class _GFDCallbacks {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GFDCallbacks(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GFDCallbacks obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fridacoreJNI.delete__GFDCallbacks(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setOn_fd_opened(SWIGTYPE_p_f_int_p_q_const__char__void value) {
    fridacoreJNI._GFDCallbacks_on_fd_opened_set(swigCPtr, this, SWIGTYPE_p_f_int_p_q_const__char__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_int_p_q_const__char__void getOn_fd_opened() {
    long cPtr = fridacoreJNI._GFDCallbacks_on_fd_opened_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_int_p_q_const__char__void(cPtr, false);
  }

  public void setOn_fd_closed(SWIGTYPE_p_f_int_p_q_const__char__void value) {
    fridacoreJNI._GFDCallbacks_on_fd_closed_set(swigCPtr, this, SWIGTYPE_p_f_int_p_q_const__char__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_int_p_q_const__char__void getOn_fd_closed() {
    long cPtr = fridacoreJNI._GFDCallbacks_on_fd_closed_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_int_p_q_const__char__void(cPtr, false);
  }

  public _GFDCallbacks() {
    this(fridacoreJNI.new__GFDCallbacks(), true);
  }

}
