/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public class _GFloatIEEE754 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GFloatIEEE754(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GFloatIEEE754 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fridacoreJNI.delete__GFloatIEEE754(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setV_float(float value) {
    fridacoreJNI._GFloatIEEE754_v_float_set(swigCPtr, this, value);
  }

  public float getV_float() {
    return fridacoreJNI._GFloatIEEE754_v_float_get(swigCPtr, this);
  }

  public _GFloatIEEE754() {
    this(fridacoreJNI.new__GFloatIEEE754(), true);
  }

}
