/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public class _GFlagsClass {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GFlagsClass(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GFlagsClass obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fridacoreJNI.delete__GFlagsClass(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setG_type_class(_GTypeClass value) {
    fridacoreJNI._GFlagsClass_g_type_class_set(swigCPtr, this, _GTypeClass.getCPtr(value), value);
  }

  public _GTypeClass getG_type_class() {
    long cPtr = fridacoreJNI._GFlagsClass_g_type_class_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GTypeClass(cPtr, false);
  }

  public void setMask(long value) {
    fridacoreJNI._GFlagsClass_mask_set(swigCPtr, this, value);
  }

  public long getMask() {
    return fridacoreJNI._GFlagsClass_mask_get(swigCPtr, this);
  }

  public void setN_values(long value) {
    fridacoreJNI._GFlagsClass_n_values_set(swigCPtr, this, value);
  }

  public long getN_values() {
    return fridacoreJNI._GFlagsClass_n_values_get(swigCPtr, this);
  }

  public void setValues(_GFlagsValue value) {
    fridacoreJNI._GFlagsClass_values_set(swigCPtr, this, _GFlagsValue.getCPtr(value), value);
  }

  public _GFlagsValue getValues() {
    long cPtr = fridacoreJNI._GFlagsClass_values_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GFlagsValue(cPtr, false);
  }

  public _GFlagsClass() {
    this(fridacoreJNI.new__GFlagsClass(), true);
  }

}
