/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public class _GIconIface {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GIconIface(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GIconIface obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fridacoreJNI.delete__GIconIface(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setG_iface(_GTypeInterface value) {
    fridacoreJNI._GIconIface_g_iface_set(swigCPtr, this, _GTypeInterface.getCPtr(value), value);
  }

  public _GTypeInterface getG_iface() {
    long cPtr = fridacoreJNI._GIconIface_g_iface_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GTypeInterface(cPtr, false);
  }

  public void setHash(SWIGTYPE_p_f_p__GIcon__unsigned_int value) {
    fridacoreJNI._GIconIface_hash_set(swigCPtr, this, SWIGTYPE_p_f_p__GIcon__unsigned_int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GIcon__unsigned_int getHash() {
    long cPtr = fridacoreJNI._GIconIface_hash_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GIcon__unsigned_int(cPtr, false);
  }

  public void setEqual(SWIGTYPE_p_f_p__GIcon_p__GIcon__int value) {
    fridacoreJNI._GIconIface_equal_set(swigCPtr, this, SWIGTYPE_p_f_p__GIcon_p__GIcon__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GIcon_p__GIcon__int getEqual() {
    long cPtr = fridacoreJNI._GIconIface_equal_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GIcon_p__GIcon__int(cPtr, false);
  }

  public void setTo_tokens(SWIGTYPE_p_f_p__GIcon_p__GPtrArray_p_int__int value) {
    fridacoreJNI._GIconIface_to_tokens_set(swigCPtr, this, SWIGTYPE_p_f_p__GIcon_p__GPtrArray_p_int__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GIcon_p__GPtrArray_p_int__int getTo_tokens() {
    long cPtr = fridacoreJNI._GIconIface_to_tokens_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GIcon_p__GPtrArray_p_int__int(cPtr, false);
  }

  public void setFrom_tokens(SWIGTYPE_p_f_p_p_char_int_int_p_p__GError__p__GIcon value) {
    fridacoreJNI._GIconIface_from_tokens_set(swigCPtr, this, SWIGTYPE_p_f_p_p_char_int_int_p_p__GError__p__GIcon.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_p_char_int_int_p_p__GError__p__GIcon getFrom_tokens() {
    long cPtr = fridacoreJNI._GIconIface_from_tokens_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_p_char_int_int_p_p__GError__p__GIcon(cPtr, false);
  }

  public void setSerialize(SWIGTYPE_p_f_p__GIcon__p__GVariant value) {
    fridacoreJNI._GIconIface_serialize_set(swigCPtr, this, SWIGTYPE_p_f_p__GIcon__p__GVariant.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GIcon__p__GVariant getSerialize() {
    long cPtr = fridacoreJNI._GIconIface_serialize_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GIcon__p__GVariant(cPtr, false);
  }

  public _GIconIface() {
    this(fridacoreJNI.new__GIconIface(), true);
  }

}
