/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public class _GInetAddressClass {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GInetAddressClass(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GInetAddressClass obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fridacoreJNI.delete__GInetAddressClass(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setParent_class(_GObjectClass value) {
    fridacoreJNI._GInetAddressClass_parent_class_set(swigCPtr, this, _GObjectClass.getCPtr(value), value);
  }

  public _GObjectClass getParent_class() {
    long cPtr = fridacoreJNI._GInetAddressClass_parent_class_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GObjectClass(cPtr, false);
  }

  public void setTo_string(SWIGTYPE_p_f_p__GInetAddress__p_char value) {
    fridacoreJNI._GInetAddressClass_to_string_set(swigCPtr, this, SWIGTYPE_p_f_p__GInetAddress__p_char.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GInetAddress__p_char getTo_string() {
    long cPtr = fridacoreJNI._GInetAddressClass_to_string_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GInetAddress__p_char(cPtr, false);
  }

  public void setTo_bytes(SWIGTYPE_p_f_p__GInetAddress__p_unsigned_char value) {
    fridacoreJNI._GInetAddressClass_to_bytes_set(swigCPtr, this, SWIGTYPE_p_f_p__GInetAddress__p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GInetAddress__p_unsigned_char getTo_bytes() {
    long cPtr = fridacoreJNI._GInetAddressClass_to_bytes_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GInetAddress__p_unsigned_char(cPtr, false);
  }

  public _GInetAddressClass() {
    this(fridacoreJNI.new__GInetAddressClass(), true);
  }

}
