/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public class _GIOFuncs {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GIOFuncs(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GIOFuncs obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fridacoreJNI.delete__GIOFuncs(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setIo_read(SWIGTYPE_p_f_p__GIOChannel_p_char_unsigned_long_p_unsigned_long_p_p__GError__GIOStatus value) {
    fridacoreJNI._GIOFuncs_io_read_set(swigCPtr, this, SWIGTYPE_p_f_p__GIOChannel_p_char_unsigned_long_p_unsigned_long_p_p__GError__GIOStatus.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GIOChannel_p_char_unsigned_long_p_unsigned_long_p_p__GError__GIOStatus getIo_read() {
    long cPtr = fridacoreJNI._GIOFuncs_io_read_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GIOChannel_p_char_unsigned_long_p_unsigned_long_p_p__GError__GIOStatus(cPtr, false);
  }

  public void setIo_write(SWIGTYPE_p_f_p__GIOChannel_p_q_const__char_unsigned_long_p_unsigned_long_p_p__GError__GIOStatus value) {
    fridacoreJNI._GIOFuncs_io_write_set(swigCPtr, this, SWIGTYPE_p_f_p__GIOChannel_p_q_const__char_unsigned_long_p_unsigned_long_p_p__GError__GIOStatus.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GIOChannel_p_q_const__char_unsigned_long_p_unsigned_long_p_p__GError__GIOStatus getIo_write() {
    long cPtr = fridacoreJNI._GIOFuncs_io_write_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GIOChannel_p_q_const__char_unsigned_long_p_unsigned_long_p_p__GError__GIOStatus(cPtr, false);
  }

  public void setIo_seek(SWIGTYPE_p_f_p__GIOChannel_long_enum_GSeekType_p_p__GError__GIOStatus value) {
    fridacoreJNI._GIOFuncs_io_seek_set(swigCPtr, this, SWIGTYPE_p_f_p__GIOChannel_long_enum_GSeekType_p_p__GError__GIOStatus.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GIOChannel_long_enum_GSeekType_p_p__GError__GIOStatus getIo_seek() {
    long cPtr = fridacoreJNI._GIOFuncs_io_seek_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GIOChannel_long_enum_GSeekType_p_p__GError__GIOStatus(cPtr, false);
  }

  public void setIo_close(SWIGTYPE_p_f_p__GIOChannel_p_p__GError__GIOStatus value) {
    fridacoreJNI._GIOFuncs_io_close_set(swigCPtr, this, SWIGTYPE_p_f_p__GIOChannel_p_p__GError__GIOStatus.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GIOChannel_p_p__GError__GIOStatus getIo_close() {
    long cPtr = fridacoreJNI._GIOFuncs_io_close_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GIOChannel_p_p__GError__GIOStatus(cPtr, false);
  }

  public void setIo_create_watch(SWIGTYPE_p_f_p_GIOChannel_GIOCondition__p__GSource value) {
    fridacoreJNI._GIOFuncs_io_create_watch_set(swigCPtr, this, SWIGTYPE_p_f_p_GIOChannel_GIOCondition__p__GSource.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_GIOChannel_GIOCondition__p__GSource getIo_create_watch() {
    long cPtr = fridacoreJNI._GIOFuncs_io_create_watch_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_GIOChannel_GIOCondition__p__GSource(cPtr, false);
  }

  public void setIo_free(SWIGTYPE_p_f_p__GIOChannel__void value) {
    fridacoreJNI._GIOFuncs_io_free_set(swigCPtr, this, SWIGTYPE_p_f_p__GIOChannel__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GIOChannel__void getIo_free() {
    long cPtr = fridacoreJNI._GIOFuncs_io_free_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GIOChannel__void(cPtr, false);
  }

  public void setIo_set_flags(SWIGTYPE_p_f_p__GIOChannel_enum_GIOFlags_p_p__GError__GIOStatus value) {
    fridacoreJNI._GIOFuncs_io_set_flags_set(swigCPtr, this, SWIGTYPE_p_f_p__GIOChannel_enum_GIOFlags_p_p__GError__GIOStatus.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GIOChannel_enum_GIOFlags_p_p__GError__GIOStatus getIo_set_flags() {
    long cPtr = fridacoreJNI._GIOFuncs_io_set_flags_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GIOChannel_enum_GIOFlags_p_p__GError__GIOStatus(cPtr, false);
  }

  public void setIo_get_flags(SWIGTYPE_p_f_p__GIOChannel__GIOFlags value) {
    fridacoreJNI._GIOFuncs_io_get_flags_set(swigCPtr, this, SWIGTYPE_p_f_p__GIOChannel__GIOFlags.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GIOChannel__GIOFlags getIo_get_flags() {
    long cPtr = fridacoreJNI._GIOFuncs_io_get_flags_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GIOChannel__GIOFlags(cPtr, false);
  }

  public _GIOFuncs() {
    this(fridacoreJNI.new__GIOFuncs(), true);
  }

}
