/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public class _GMemoryInputStream {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GMemoryInputStream(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GMemoryInputStream obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fridacoreJNI.delete__GMemoryInputStream(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setParent_instance(_GInputStream value) {
    fridacoreJNI._GMemoryInputStream_parent_instance_set(swigCPtr, this, _GInputStream.getCPtr(value), value);
  }

  public _GInputStream getParent_instance() {
    long cPtr = fridacoreJNI._GMemoryInputStream_parent_instance_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GInputStream(cPtr, false);
  }

  public void setPriv(SWIGTYPE_p__GMemoryInputStreamPrivate value) {
    fridacoreJNI._GMemoryInputStream_priv_set(swigCPtr, this, SWIGTYPE_p__GMemoryInputStreamPrivate.getCPtr(value));
  }

  public SWIGTYPE_p__GMemoryInputStreamPrivate getPriv() {
    long cPtr = fridacoreJNI._GMemoryInputStream_priv_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p__GMemoryInputStreamPrivate(cPtr, false);
  }

  public _GMemoryInputStream() {
    this(fridacoreJNI.new__GMemoryInputStream(), true);
  }

}
