/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public class _GObjectClass {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GObjectClass(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GObjectClass obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fridacoreJNI.delete__GObjectClass(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setG_type_class(_GTypeClass value) {
    fridacoreJNI._GObjectClass_g_type_class_set(swigCPtr, this, _GTypeClass.getCPtr(value), value);
  }

  public _GTypeClass getG_type_class() {
    long cPtr = fridacoreJNI._GObjectClass_g_type_class_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GTypeClass(cPtr, false);
  }

  public void setConstruct_properties(_GSList value) {
    fridacoreJNI._GObjectClass_construct_properties_set(swigCPtr, this, _GSList.getCPtr(value), value);
  }

  public _GSList getConstruct_properties() {
    long cPtr = fridacoreJNI._GObjectClass_construct_properties_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GSList(cPtr, false);
  }

  public void setConstructor(SWIGTYPE_p_f_GType_guint_p_GObjectConstructParam__p__GObject value) {
    fridacoreJNI._GObjectClass_constructor_set(swigCPtr, this, SWIGTYPE_p_f_GType_guint_p_GObjectConstructParam__p__GObject.getCPtr(value));
  }

  public SWIGTYPE_p_f_GType_guint_p_GObjectConstructParam__p__GObject getConstructor() {
    long cPtr = fridacoreJNI._GObjectClass_constructor_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_GType_guint_p_GObjectConstructParam__p__GObject(cPtr, false);
  }

  public void setSet_property(SWIGTYPE_p_f_p__GObject_unsigned_int_p_q_const___GValue_p__GParamSpec__void value) {
    fridacoreJNI._GObjectClass_set_property_set(swigCPtr, this, SWIGTYPE_p_f_p__GObject_unsigned_int_p_q_const___GValue_p__GParamSpec__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GObject_unsigned_int_p_q_const___GValue_p__GParamSpec__void getSet_property() {
    long cPtr = fridacoreJNI._GObjectClass_set_property_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GObject_unsigned_int_p_q_const___GValue_p__GParamSpec__void(cPtr, false);
  }

  public void setGet_property(SWIGTYPE_p_f_p__GObject_unsigned_int_p__GValue_p__GParamSpec__void value) {
    fridacoreJNI._GObjectClass_get_property_set(swigCPtr, this, SWIGTYPE_p_f_p__GObject_unsigned_int_p__GValue_p__GParamSpec__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GObject_unsigned_int_p__GValue_p__GParamSpec__void getGet_property() {
    long cPtr = fridacoreJNI._GObjectClass_get_property_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GObject_unsigned_int_p__GValue_p__GParamSpec__void(cPtr, false);
  }

  public void setDispose(SWIGTYPE_p_f_p__GObject__void value) {
    fridacoreJNI._GObjectClass_dispose_set(swigCPtr, this, SWIGTYPE_p_f_p__GObject__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GObject__void getDispose() {
    long cPtr = fridacoreJNI._GObjectClass_dispose_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GObject__void(cPtr, false);
  }

  public void setFinalize(SWIGTYPE_p_f_p__GObject__void value) {
    fridacoreJNI._GObjectClass_finalize_set(swigCPtr, this, SWIGTYPE_p_f_p__GObject__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GObject__void getFinalize() {
    long cPtr = fridacoreJNI._GObjectClass_finalize_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GObject__void(cPtr, false);
  }

  public void setDispatch_properties_changed(SWIGTYPE_p_f_p__GObject_unsigned_int_p_p__GParamSpec__void value) {
    fridacoreJNI._GObjectClass_dispatch_properties_changed_set(swigCPtr, this, SWIGTYPE_p_f_p__GObject_unsigned_int_p_p__GParamSpec__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GObject_unsigned_int_p_p__GParamSpec__void getDispatch_properties_changed() {
    long cPtr = fridacoreJNI._GObjectClass_dispatch_properties_changed_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GObject_unsigned_int_p_p__GParamSpec__void(cPtr, false);
  }

  public void setNotify(SWIGTYPE_p_f_p__GObject_p__GParamSpec__void value) {
    fridacoreJNI._GObjectClass_notify_set(swigCPtr, this, SWIGTYPE_p_f_p__GObject_p__GParamSpec__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GObject_p__GParamSpec__void getNotify() {
    long cPtr = fridacoreJNI._GObjectClass_notify_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GObject_p__GParamSpec__void(cPtr, false);
  }

  public void setConstructed(SWIGTYPE_p_f_p__GObject__void value) {
    fridacoreJNI._GObjectClass_constructed_set(swigCPtr, this, SWIGTYPE_p_f_p__GObject__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GObject__void getConstructed() {
    long cPtr = fridacoreJNI._GObjectClass_constructed_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GObject__void(cPtr, false);
  }

  public void setFlags(long value) {
    fridacoreJNI._GObjectClass_flags_set(swigCPtr, this, value);
  }

  public long getFlags() {
    return fridacoreJNI._GObjectClass_flags_get(swigCPtr, this);
  }

  public void setPdummy(SWIGTYPE_p_p_void value) {
    fridacoreJNI._GObjectClass_pdummy_set(swigCPtr, this, SWIGTYPE_p_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_p_void getPdummy() {
    long cPtr = fridacoreJNI._GObjectClass_pdummy_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_void(cPtr, false);
  }

  public _GObjectClass() {
    this(fridacoreJNI.new__GObjectClass(), true);
  }

}
