/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public class _GOutputMessage {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GOutputMessage(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GOutputMessage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fridacoreJNI.delete__GOutputMessage(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAddress(_GSocketAddress value) {
    fridacoreJNI._GOutputMessage_address_set(swigCPtr, this, _GSocketAddress.getCPtr(value), value);
  }

  public _GSocketAddress getAddress() {
    long cPtr = fridacoreJNI._GOutputMessage_address_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GSocketAddress(cPtr, false);
  }

  public void setVectors(_GOutputVector value) {
    fridacoreJNI._GOutputMessage_vectors_set(swigCPtr, this, _GOutputVector.getCPtr(value), value);
  }

  public _GOutputVector getVectors() {
    long cPtr = fridacoreJNI._GOutputMessage_vectors_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GOutputVector(cPtr, false);
  }

  public void setNum_vectors(long value) {
    fridacoreJNI._GOutputMessage_num_vectors_set(swigCPtr, this, value);
  }

  public long getNum_vectors() {
    return fridacoreJNI._GOutputMessage_num_vectors_get(swigCPtr, this);
  }

  public void setBytes_sent(long value) {
    fridacoreJNI._GOutputMessage_bytes_sent_set(swigCPtr, this, value);
  }

  public long getBytes_sent() {
    return fridacoreJNI._GOutputMessage_bytes_sent_get(swigCPtr, this);
  }

  public void setControl_messages(SWIGTYPE_p_p__GSocketControlMessage value) {
    fridacoreJNI._GOutputMessage_control_messages_set(swigCPtr, this, SWIGTYPE_p_p__GSocketControlMessage.getCPtr(value));
  }

  public SWIGTYPE_p_p__GSocketControlMessage getControl_messages() {
    long cPtr = fridacoreJNI._GOutputMessage_control_messages_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p__GSocketControlMessage(cPtr, false);
  }

  public void setNum_control_messages(long value) {
    fridacoreJNI._GOutputMessage_num_control_messages_set(swigCPtr, this, value);
  }

  public long getNum_control_messages() {
    return fridacoreJNI._GOutputMessage_num_control_messages_get(swigCPtr, this);
  }

  public _GOutputMessage() {
    this(fridacoreJNI.new__GOutputMessage(), true);
  }

}
