/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public class _GOutputStreamClass {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GOutputStreamClass(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GOutputStreamClass obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fridacoreJNI.delete__GOutputStreamClass(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setParent_class(_GObjectClass value) {
    fridacoreJNI._GOutputStreamClass_parent_class_set(swigCPtr, this, _GObjectClass.getCPtr(value), value);
  }

  public _GObjectClass getParent_class() {
    long cPtr = fridacoreJNI._GOutputStreamClass_parent_class_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GObjectClass(cPtr, false);
  }

  public void setWrite_fn(SWIGTYPE_p_f_p__GOutputStream_p_q_const__void_unsigned_long_p__GCancellable_p_p__GError__long value) {
    fridacoreJNI._GOutputStreamClass_write_fn_set(swigCPtr, this, SWIGTYPE_p_f_p__GOutputStream_p_q_const__void_unsigned_long_p__GCancellable_p_p__GError__long.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GOutputStream_p_q_const__void_unsigned_long_p__GCancellable_p_p__GError__long getWrite_fn() {
    long cPtr = fridacoreJNI._GOutputStreamClass_write_fn_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GOutputStream_p_q_const__void_unsigned_long_p__GCancellable_p_p__GError__long(cPtr, false);
  }

  public void setSplice(SWIGTYPE_p_f_p__GOutputStream_p__GInputStream_enum_GOutputStreamSpliceFlags_p__GCancellable_p_p__GError__long value) {
    fridacoreJNI._GOutputStreamClass_splice_set(swigCPtr, this, SWIGTYPE_p_f_p__GOutputStream_p__GInputStream_enum_GOutputStreamSpliceFlags_p__GCancellable_p_p__GError__long.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GOutputStream_p__GInputStream_enum_GOutputStreamSpliceFlags_p__GCancellable_p_p__GError__long getSplice() {
    long cPtr = fridacoreJNI._GOutputStreamClass_splice_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GOutputStream_p__GInputStream_enum_GOutputStreamSpliceFlags_p__GCancellable_p_p__GError__long(cPtr, false);
  }

  public void setFlush(SWIGTYPE_p_f_p__GOutputStream_p__GCancellable_p_p__GError__int value) {
    fridacoreJNI._GOutputStreamClass_flush_set(swigCPtr, this, SWIGTYPE_p_f_p__GOutputStream_p__GCancellable_p_p__GError__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GOutputStream_p__GCancellable_p_p__GError__int getFlush() {
    long cPtr = fridacoreJNI._GOutputStreamClass_flush_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GOutputStream_p__GCancellable_p_p__GError__int(cPtr, false);
  }

  public void setClose_fn(SWIGTYPE_p_f_p__GOutputStream_p__GCancellable_p_p__GError__int value) {
    fridacoreJNI._GOutputStreamClass_close_fn_set(swigCPtr, this, SWIGTYPE_p_f_p__GOutputStream_p__GCancellable_p_p__GError__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GOutputStream_p__GCancellable_p_p__GError__int getClose_fn() {
    long cPtr = fridacoreJNI._GOutputStreamClass_close_fn_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GOutputStream_p__GCancellable_p_p__GError__int(cPtr, false);
  }

  public void setWrite_async(SWIGTYPE_p_f_p__GOutputStream_p_q_const__void_unsigned_long_int_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void value) {
    fridacoreJNI._GOutputStreamClass_write_async_set(swigCPtr, this, SWIGTYPE_p_f_p__GOutputStream_p_q_const__void_unsigned_long_int_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GOutputStream_p_q_const__void_unsigned_long_int_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void getWrite_async() {
    long cPtr = fridacoreJNI._GOutputStreamClass_write_async_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GOutputStream_p_q_const__void_unsigned_long_int_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void(cPtr, false);
  }

  public void setWrite_finish(SWIGTYPE_p_f_p__GOutputStream_p__GAsyncResult_p_p__GError__long value) {
    fridacoreJNI._GOutputStreamClass_write_finish_set(swigCPtr, this, SWIGTYPE_p_f_p__GOutputStream_p__GAsyncResult_p_p__GError__long.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GOutputStream_p__GAsyncResult_p_p__GError__long getWrite_finish() {
    long cPtr = fridacoreJNI._GOutputStreamClass_write_finish_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GOutputStream_p__GAsyncResult_p_p__GError__long(cPtr, false);
  }

  public void setSplice_async(SWIGTYPE_p_f_p__GOutputStream_p__GInputStream_enum_GOutputStreamSpliceFlags_int_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void value) {
    fridacoreJNI._GOutputStreamClass_splice_async_set(swigCPtr, this, SWIGTYPE_p_f_p__GOutputStream_p__GInputStream_enum_GOutputStreamSpliceFlags_int_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GOutputStream_p__GInputStream_enum_GOutputStreamSpliceFlags_int_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void getSplice_async() {
    long cPtr = fridacoreJNI._GOutputStreamClass_splice_async_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GOutputStream_p__GInputStream_enum_GOutputStreamSpliceFlags_int_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void(cPtr, false);
  }

  public void setSplice_finish(SWIGTYPE_p_f_p__GOutputStream_p__GAsyncResult_p_p__GError__long value) {
    fridacoreJNI._GOutputStreamClass_splice_finish_set(swigCPtr, this, SWIGTYPE_p_f_p__GOutputStream_p__GAsyncResult_p_p__GError__long.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GOutputStream_p__GAsyncResult_p_p__GError__long getSplice_finish() {
    long cPtr = fridacoreJNI._GOutputStreamClass_splice_finish_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GOutputStream_p__GAsyncResult_p_p__GError__long(cPtr, false);
  }

  public void setFlush_async(SWIGTYPE_p_f_p__GOutputStream_int_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void value) {
    fridacoreJNI._GOutputStreamClass_flush_async_set(swigCPtr, this, SWIGTYPE_p_f_p__GOutputStream_int_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GOutputStream_int_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void getFlush_async() {
    long cPtr = fridacoreJNI._GOutputStreamClass_flush_async_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GOutputStream_int_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void(cPtr, false);
  }

  public void setFlush_finish(SWIGTYPE_p_f_p__GOutputStream_p__GAsyncResult_p_p__GError__int value) {
    fridacoreJNI._GOutputStreamClass_flush_finish_set(swigCPtr, this, SWIGTYPE_p_f_p__GOutputStream_p__GAsyncResult_p_p__GError__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GOutputStream_p__GAsyncResult_p_p__GError__int getFlush_finish() {
    long cPtr = fridacoreJNI._GOutputStreamClass_flush_finish_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GOutputStream_p__GAsyncResult_p_p__GError__int(cPtr, false);
  }

  public void setClose_async(SWIGTYPE_p_f_p__GOutputStream_int_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void value) {
    fridacoreJNI._GOutputStreamClass_close_async_set(swigCPtr, this, SWIGTYPE_p_f_p__GOutputStream_int_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GOutputStream_int_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void getClose_async() {
    long cPtr = fridacoreJNI._GOutputStreamClass_close_async_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GOutputStream_int_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void(cPtr, false);
  }

  public void setClose_finish(SWIGTYPE_p_f_p__GOutputStream_p__GAsyncResult_p_p__GError__int value) {
    fridacoreJNI._GOutputStreamClass_close_finish_set(swigCPtr, this, SWIGTYPE_p_f_p__GOutputStream_p__GAsyncResult_p_p__GError__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GOutputStream_p__GAsyncResult_p_p__GError__int getClose_finish() {
    long cPtr = fridacoreJNI._GOutputStreamClass_close_finish_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GOutputStream_p__GAsyncResult_p_p__GError__int(cPtr, false);
  }

  public void setWritev_fn(SWIGTYPE_p_f_p__GOutputStream_p_q_const___GOutputVector_unsigned_long_p_unsigned_long_p__GCancellable_p_p__GError__int value) {
    fridacoreJNI._GOutputStreamClass_writev_fn_set(swigCPtr, this, SWIGTYPE_p_f_p__GOutputStream_p_q_const___GOutputVector_unsigned_long_p_unsigned_long_p__GCancellable_p_p__GError__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GOutputStream_p_q_const___GOutputVector_unsigned_long_p_unsigned_long_p__GCancellable_p_p__GError__int getWritev_fn() {
    long cPtr = fridacoreJNI._GOutputStreamClass_writev_fn_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GOutputStream_p_q_const___GOutputVector_unsigned_long_p_unsigned_long_p__GCancellable_p_p__GError__int(cPtr, false);
  }

  public void setWritev_async(SWIGTYPE_p_f_p__GOutputStream_p_q_const___GOutputVector_unsigned_long_int_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void value) {
    fridacoreJNI._GOutputStreamClass_writev_async_set(swigCPtr, this, SWIGTYPE_p_f_p__GOutputStream_p_q_const___GOutputVector_unsigned_long_int_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GOutputStream_p_q_const___GOutputVector_unsigned_long_int_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void getWritev_async() {
    long cPtr = fridacoreJNI._GOutputStreamClass_writev_async_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GOutputStream_p_q_const___GOutputVector_unsigned_long_int_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void(cPtr, false);
  }

  public void setWritev_finish(SWIGTYPE_p_f_p__GOutputStream_p__GAsyncResult_p_unsigned_long_p_p__GError__int value) {
    fridacoreJNI._GOutputStreamClass_writev_finish_set(swigCPtr, this, SWIGTYPE_p_f_p__GOutputStream_p__GAsyncResult_p_unsigned_long_p_p__GError__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GOutputStream_p__GAsyncResult_p_unsigned_long_p_p__GError__int getWritev_finish() {
    long cPtr = fridacoreJNI._GOutputStreamClass_writev_finish_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GOutputStream_p__GAsyncResult_p_unsigned_long_p_p__GError__int(cPtr, false);
  }

  public void set_g_reserved4(SWIGTYPE_p_f_void__void value) {
    fridacoreJNI._GOutputStreamClass__g_reserved4_set(swigCPtr, this, SWIGTYPE_p_f_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_void__void get_g_reserved4() {
    long cPtr = fridacoreJNI._GOutputStreamClass__g_reserved4_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_void__void(cPtr, false);
  }

  public void set_g_reserved5(SWIGTYPE_p_f_void__void value) {
    fridacoreJNI._GOutputStreamClass__g_reserved5_set(swigCPtr, this, SWIGTYPE_p_f_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_void__void get_g_reserved5() {
    long cPtr = fridacoreJNI._GOutputStreamClass__g_reserved5_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_void__void(cPtr, false);
  }

  public void set_g_reserved6(SWIGTYPE_p_f_void__void value) {
    fridacoreJNI._GOutputStreamClass__g_reserved6_set(swigCPtr, this, SWIGTYPE_p_f_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_void__void get_g_reserved6() {
    long cPtr = fridacoreJNI._GOutputStreamClass__g_reserved6_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_void__void(cPtr, false);
  }

  public void set_g_reserved7(SWIGTYPE_p_f_void__void value) {
    fridacoreJNI._GOutputStreamClass__g_reserved7_set(swigCPtr, this, SWIGTYPE_p_f_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_void__void get_g_reserved7() {
    long cPtr = fridacoreJNI._GOutputStreamClass__g_reserved7_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_void__void(cPtr, false);
  }

  public void set_g_reserved8(SWIGTYPE_p_f_void__void value) {
    fridacoreJNI._GOutputStreamClass__g_reserved8_set(swigCPtr, this, SWIGTYPE_p_f_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_void__void get_g_reserved8() {
    long cPtr = fridacoreJNI._GOutputStreamClass__g_reserved8_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_void__void(cPtr, false);
  }

  public _GOutputStreamClass() {
    this(fridacoreJNI.new__GOutputStreamClass(), true);
  }

}
