/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public class _GParamSpec {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GParamSpec(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GParamSpec obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fridacoreJNI.delete__GParamSpec(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setG_type_instance(_GTypeInstance value) {
    fridacoreJNI._GParamSpec_g_type_instance_set(swigCPtr, this, _GTypeInstance.getCPtr(value), value);
  }

  public _GTypeInstance getG_type_instance() {
    long cPtr = fridacoreJNI._GParamSpec_g_type_instance_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GTypeInstance(cPtr, false);
  }

  public void setName(String value) {
    fridacoreJNI._GParamSpec_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return fridacoreJNI._GParamSpec_name_get(swigCPtr, this);
  }

  public void setFlags(GParamFlags value) {
    fridacoreJNI._GParamSpec_flags_set(swigCPtr, this, value.swigValue());
  }

  public GParamFlags getFlags() {
    return GParamFlags.swigToEnum(fridacoreJNI._GParamSpec_flags_get(swigCPtr, this));
  }

  public void setValue_type(long value) {
    fridacoreJNI._GParamSpec_value_type_set(swigCPtr, this, value);
  }

  public long getValue_type() {
    return fridacoreJNI._GParamSpec_value_type_get(swigCPtr, this);
  }

  public void setOwner_type(long value) {
    fridacoreJNI._GParamSpec_owner_type_set(swigCPtr, this, value);
  }

  public long getOwner_type() {
    return fridacoreJNI._GParamSpec_owner_type_get(swigCPtr, this);
  }

  public void set_nick(String value) {
    fridacoreJNI._GParamSpec__nick_set(swigCPtr, this, value);
  }

  public String get_nick() {
    return fridacoreJNI._GParamSpec__nick_get(swigCPtr, this);
  }

  public void set_blurb(String value) {
    fridacoreJNI._GParamSpec__blurb_set(swigCPtr, this, value);
  }

  public String get_blurb() {
    return fridacoreJNI._GParamSpec__blurb_get(swigCPtr, this);
  }

  public void setQdata(SWIGTYPE_p__GData value) {
    fridacoreJNI._GParamSpec_qdata_set(swigCPtr, this, SWIGTYPE_p__GData.getCPtr(value));
  }

  public SWIGTYPE_p__GData getQdata() {
    long cPtr = fridacoreJNI._GParamSpec_qdata_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p__GData(cPtr, false);
  }

  public void setRef_count(long value) {
    fridacoreJNI._GParamSpec_ref_count_set(swigCPtr, this, value);
  }

  public long getRef_count() {
    return fridacoreJNI._GParamSpec_ref_count_get(swigCPtr, this);
  }

  public void setParam_id(long value) {
    fridacoreJNI._GParamSpec_param_id_set(swigCPtr, this, value);
  }

  public long getParam_id() {
    return fridacoreJNI._GParamSpec_param_id_get(swigCPtr, this);
  }

  public _GParamSpec() {
    this(fridacoreJNI.new__GParamSpec(), true);
  }

}
