/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public class _GParamSpecTypeInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GParamSpecTypeInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GParamSpecTypeInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fridacoreJNI.delete__GParamSpecTypeInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setInstance_size(int value) {
    fridacoreJNI._GParamSpecTypeInfo_instance_size_set(swigCPtr, this, value);
  }

  public int getInstance_size() {
    return fridacoreJNI._GParamSpecTypeInfo_instance_size_get(swigCPtr, this);
  }

  public void setN_preallocs(int value) {
    fridacoreJNI._GParamSpecTypeInfo_n_preallocs_set(swigCPtr, this, value);
  }

  public int getN_preallocs() {
    return fridacoreJNI._GParamSpecTypeInfo_n_preallocs_get(swigCPtr, this);
  }

  public void setInstance_init(SWIGTYPE_p_f_p__GParamSpec__void value) {
    fridacoreJNI._GParamSpecTypeInfo_instance_init_set(swigCPtr, this, SWIGTYPE_p_f_p__GParamSpec__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GParamSpec__void getInstance_init() {
    long cPtr = fridacoreJNI._GParamSpecTypeInfo_instance_init_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GParamSpec__void(cPtr, false);
  }

  public void setValue_type(long value) {
    fridacoreJNI._GParamSpecTypeInfo_value_type_set(swigCPtr, this, value);
  }

  public long getValue_type() {
    return fridacoreJNI._GParamSpecTypeInfo_value_type_get(swigCPtr, this);
  }

  public void setFinalize(SWIGTYPE_p_f_p__GParamSpec__void value) {
    fridacoreJNI._GParamSpecTypeInfo_finalize_set(swigCPtr, this, SWIGTYPE_p_f_p__GParamSpec__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GParamSpec__void getFinalize() {
    long cPtr = fridacoreJNI._GParamSpecTypeInfo_finalize_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GParamSpec__void(cPtr, false);
  }

  public void setValue_set_default(SWIGTYPE_p_f_p__GParamSpec_p__GValue__void value) {
    fridacoreJNI._GParamSpecTypeInfo_value_set_default_set(swigCPtr, this, SWIGTYPE_p_f_p__GParamSpec_p__GValue__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GParamSpec_p__GValue__void getValue_set_default() {
    long cPtr = fridacoreJNI._GParamSpecTypeInfo_value_set_default_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GParamSpec_p__GValue__void(cPtr, false);
  }

  public void setValue_validate(SWIGTYPE_p_f_p__GParamSpec_p__GValue__int value) {
    fridacoreJNI._GParamSpecTypeInfo_value_validate_set(swigCPtr, this, SWIGTYPE_p_f_p__GParamSpec_p__GValue__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GParamSpec_p__GValue__int getValue_validate() {
    long cPtr = fridacoreJNI._GParamSpecTypeInfo_value_validate_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GParamSpec_p__GValue__int(cPtr, false);
  }

  public void setValues_cmp(SWIGTYPE_p_f_p__GParamSpec_p_q_const___GValue_p_q_const___GValue__int value) {
    fridacoreJNI._GParamSpecTypeInfo_values_cmp_set(swigCPtr, this, SWIGTYPE_p_f_p__GParamSpec_p_q_const___GValue_p_q_const___GValue__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GParamSpec_p_q_const___GValue_p_q_const___GValue__int getValues_cmp() {
    long cPtr = fridacoreJNI._GParamSpecTypeInfo_values_cmp_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GParamSpec_p_q_const___GValue_p_q_const___GValue__int(cPtr, false);
  }

  public _GParamSpecTypeInfo() {
    this(fridacoreJNI.new__GParamSpecTypeInfo(), true);
  }

}
