/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public class _GParamSpecChar {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GParamSpecChar(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GParamSpecChar obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fridacoreJNI.delete__GParamSpecChar(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setParent_instance(_GParamSpec value) {
    fridacoreJNI._GParamSpecChar_parent_instance_set(swigCPtr, this, _GParamSpec.getCPtr(value), value);
  }

  public _GParamSpec getParent_instance() {
    long cPtr = fridacoreJNI._GParamSpecChar_parent_instance_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GParamSpec(cPtr, false);
  }

  public void setMinimum(byte value) {
    fridacoreJNI._GParamSpecChar_minimum_set(swigCPtr, this, value);
  }

  public byte getMinimum() {
    return fridacoreJNI._GParamSpecChar_minimum_get(swigCPtr, this);
  }

  public void setMaximum(byte value) {
    fridacoreJNI._GParamSpecChar_maximum_set(swigCPtr, this, value);
  }

  public byte getMaximum() {
    return fridacoreJNI._GParamSpecChar_maximum_get(swigCPtr, this);
  }

  public void setDefault_value(byte value) {
    fridacoreJNI._GParamSpecChar_default_value_set(swigCPtr, this, value);
  }

  public byte getDefault_value() {
    return fridacoreJNI._GParamSpecChar_default_value_get(swigCPtr, this);
  }

  public _GParamSpecChar() {
    this(fridacoreJNI.new__GParamSpecChar(), true);
  }

}
