/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public class _GParamSpecLong {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GParamSpecLong(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GParamSpecLong obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fridacoreJNI.delete__GParamSpecLong(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setParent_instance(_GParamSpec value) {
    fridacoreJNI._GParamSpecLong_parent_instance_set(swigCPtr, this, _GParamSpec.getCPtr(value), value);
  }

  public _GParamSpec getParent_instance() {
    long cPtr = fridacoreJNI._GParamSpecLong_parent_instance_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GParamSpec(cPtr, false);
  }

  public void setMinimum(int value) {
    fridacoreJNI._GParamSpecLong_minimum_set(swigCPtr, this, value);
  }

  public int getMinimum() {
    return fridacoreJNI._GParamSpecLong_minimum_get(swigCPtr, this);
  }

  public void setMaximum(int value) {
    fridacoreJNI._GParamSpecLong_maximum_set(swigCPtr, this, value);
  }

  public int getMaximum() {
    return fridacoreJNI._GParamSpecLong_maximum_get(swigCPtr, this);
  }

  public void setDefault_value(int value) {
    fridacoreJNI._GParamSpecLong_default_value_set(swigCPtr, this, value);
  }

  public int getDefault_value() {
    return fridacoreJNI._GParamSpecLong_default_value_get(swigCPtr, this);
  }

  public _GParamSpecLong() {
    this(fridacoreJNI.new__GParamSpecLong(), true);
  }

}
