/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public class _GParamSpecClass {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GParamSpecClass(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GParamSpecClass obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fridacoreJNI.delete__GParamSpecClass(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setG_type_class(_GTypeClass value) {
    fridacoreJNI._GParamSpecClass_g_type_class_set(swigCPtr, this, _GTypeClass.getCPtr(value), value);
  }

  public _GTypeClass getG_type_class() {
    long cPtr = fridacoreJNI._GParamSpecClass_g_type_class_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GTypeClass(cPtr, false);
  }

  public void setValue_type(long value) {
    fridacoreJNI._GParamSpecClass_value_type_set(swigCPtr, this, value);
  }

  public long getValue_type() {
    return fridacoreJNI._GParamSpecClass_value_type_get(swigCPtr, this);
  }

  public void setFinalize(SWIGTYPE_p_f_p__GParamSpec__void value) {
    fridacoreJNI._GParamSpecClass_finalize_set(swigCPtr, this, SWIGTYPE_p_f_p__GParamSpec__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GParamSpec__void getFinalize() {
    long cPtr = fridacoreJNI._GParamSpecClass_finalize_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GParamSpec__void(cPtr, false);
  }

  public void setValue_set_default(SWIGTYPE_p_f_p__GParamSpec_p__GValue__void value) {
    fridacoreJNI._GParamSpecClass_value_set_default_set(swigCPtr, this, SWIGTYPE_p_f_p__GParamSpec_p__GValue__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GParamSpec_p__GValue__void getValue_set_default() {
    long cPtr = fridacoreJNI._GParamSpecClass_value_set_default_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GParamSpec_p__GValue__void(cPtr, false);
  }

  public void setValue_validate(SWIGTYPE_p_f_p__GParamSpec_p__GValue__int value) {
    fridacoreJNI._GParamSpecClass_value_validate_set(swigCPtr, this, SWIGTYPE_p_f_p__GParamSpec_p__GValue__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GParamSpec_p__GValue__int getValue_validate() {
    long cPtr = fridacoreJNI._GParamSpecClass_value_validate_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GParamSpec_p__GValue__int(cPtr, false);
  }

  public void setValues_cmp(SWIGTYPE_p_f_p__GParamSpec_p_q_const___GValue_p_q_const___GValue__int value) {
    fridacoreJNI._GParamSpecClass_values_cmp_set(swigCPtr, this, SWIGTYPE_p_f_p__GParamSpec_p_q_const___GValue_p_q_const___GValue__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GParamSpec_p_q_const___GValue_p_q_const___GValue__int getValues_cmp() {
    long cPtr = fridacoreJNI._GParamSpecClass_values_cmp_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GParamSpec_p_q_const___GValue_p_q_const___GValue__int(cPtr, false);
  }

  public void setDummy(SWIGTYPE_p_p_void value) {
    fridacoreJNI._GParamSpecClass_dummy_set(swigCPtr, this, SWIGTYPE_p_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_p_void getDummy() {
    long cPtr = fridacoreJNI._GParamSpecClass_dummy_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_void(cPtr, false);
  }

  public _GParamSpecClass() {
    this(fridacoreJNI.new__GParamSpecClass(), true);
  }

}
