/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public class _GProxyAddressClass {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GProxyAddressClass(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GProxyAddressClass obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fridacoreJNI.delete__GProxyAddressClass(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setParent_class(_GInetSocketAddressClass value) {
    fridacoreJNI._GProxyAddressClass_parent_class_set(swigCPtr, this, _GInetSocketAddressClass.getCPtr(value), value);
  }

  public _GInetSocketAddressClass getParent_class() {
    long cPtr = fridacoreJNI._GProxyAddressClass_parent_class_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GInetSocketAddressClass(cPtr, false);
  }

  public _GProxyAddressClass() {
    this(fridacoreJNI.new__GProxyAddressClass(), true);
  }

}
