/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public class _GResolverClass {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GResolverClass(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GResolverClass obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fridacoreJNI.delete__GResolverClass(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setParent_class(_GObjectClass value) {
    fridacoreJNI._GResolverClass_parent_class_set(swigCPtr, this, _GObjectClass.getCPtr(value), value);
  }

  public _GObjectClass getParent_class() {
    long cPtr = fridacoreJNI._GResolverClass_parent_class_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GObjectClass(cPtr, false);
  }

  public void setReload(SWIGTYPE_p_f_p__GResolver__void value) {
    fridacoreJNI._GResolverClass_reload_set(swigCPtr, this, SWIGTYPE_p_f_p__GResolver__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GResolver__void getReload() {
    long cPtr = fridacoreJNI._GResolverClass_reload_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GResolver__void(cPtr, false);
  }

  public void setLookup_by_name(SWIGTYPE_p_f_p_GResolver_p_q_const__gchar_p_GCancellable_p_p_GError__p__GList value) {
    fridacoreJNI._GResolverClass_lookup_by_name_set(swigCPtr, this, SWIGTYPE_p_f_p_GResolver_p_q_const__gchar_p_GCancellable_p_p_GError__p__GList.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_GResolver_p_q_const__gchar_p_GCancellable_p_p_GError__p__GList getLookup_by_name() {
    long cPtr = fridacoreJNI._GResolverClass_lookup_by_name_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_GResolver_p_q_const__gchar_p_GCancellable_p_p_GError__p__GList(cPtr, false);
  }

  public void setLookup_by_name_async(SWIGTYPE_p_f_p__GResolver_p_q_const__char_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void value) {
    fridacoreJNI._GResolverClass_lookup_by_name_async_set(swigCPtr, this, SWIGTYPE_p_f_p__GResolver_p_q_const__char_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GResolver_p_q_const__char_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void getLookup_by_name_async() {
    long cPtr = fridacoreJNI._GResolverClass_lookup_by_name_async_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GResolver_p_q_const__char_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void(cPtr, false);
  }

  public void setLookup_by_name_finish(SWIGTYPE_p_f_p_GResolver_p_GAsyncResult_p_p_GError__p__GList value) {
    fridacoreJNI._GResolverClass_lookup_by_name_finish_set(swigCPtr, this, SWIGTYPE_p_f_p_GResolver_p_GAsyncResult_p_p_GError__p__GList.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_GResolver_p_GAsyncResult_p_p_GError__p__GList getLookup_by_name_finish() {
    long cPtr = fridacoreJNI._GResolverClass_lookup_by_name_finish_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_GResolver_p_GAsyncResult_p_p_GError__p__GList(cPtr, false);
  }

  public void setLookup_by_address(SWIGTYPE_p_f_p__GResolver_p__GInetAddress_p__GCancellable_p_p__GError__p_char value) {
    fridacoreJNI._GResolverClass_lookup_by_address_set(swigCPtr, this, SWIGTYPE_p_f_p__GResolver_p__GInetAddress_p__GCancellable_p_p__GError__p_char.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GResolver_p__GInetAddress_p__GCancellable_p_p__GError__p_char getLookup_by_address() {
    long cPtr = fridacoreJNI._GResolverClass_lookup_by_address_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GResolver_p__GInetAddress_p__GCancellable_p_p__GError__p_char(cPtr, false);
  }

  public void setLookup_by_address_async(SWIGTYPE_p_f_p__GResolver_p__GInetAddress_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void value) {
    fridacoreJNI._GResolverClass_lookup_by_address_async_set(swigCPtr, this, SWIGTYPE_p_f_p__GResolver_p__GInetAddress_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GResolver_p__GInetAddress_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void getLookup_by_address_async() {
    long cPtr = fridacoreJNI._GResolverClass_lookup_by_address_async_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GResolver_p__GInetAddress_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void(cPtr, false);
  }

  public void setLookup_by_address_finish(SWIGTYPE_p_f_p__GResolver_p__GAsyncResult_p_p__GError__p_char value) {
    fridacoreJNI._GResolverClass_lookup_by_address_finish_set(swigCPtr, this, SWIGTYPE_p_f_p__GResolver_p__GAsyncResult_p_p__GError__p_char.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GResolver_p__GAsyncResult_p_p__GError__p_char getLookup_by_address_finish() {
    long cPtr = fridacoreJNI._GResolverClass_lookup_by_address_finish_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GResolver_p__GAsyncResult_p_p__GError__p_char(cPtr, false);
  }

  public void setLookup_service(SWIGTYPE_p_f_p_GResolver_p_q_const__gchar_p_GCancellable_p_p_GError__p__GList value) {
    fridacoreJNI._GResolverClass_lookup_service_set(swigCPtr, this, SWIGTYPE_p_f_p_GResolver_p_q_const__gchar_p_GCancellable_p_p_GError__p__GList.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_GResolver_p_q_const__gchar_p_GCancellable_p_p_GError__p__GList getLookup_service() {
    long cPtr = fridacoreJNI._GResolverClass_lookup_service_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_GResolver_p_q_const__gchar_p_GCancellable_p_p_GError__p__GList(cPtr, false);
  }

  public void setLookup_service_async(SWIGTYPE_p_f_p__GResolver_p_q_const__char_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void value) {
    fridacoreJNI._GResolverClass_lookup_service_async_set(swigCPtr, this, SWIGTYPE_p_f_p__GResolver_p_q_const__char_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GResolver_p_q_const__char_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void getLookup_service_async() {
    long cPtr = fridacoreJNI._GResolverClass_lookup_service_async_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GResolver_p_q_const__char_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void(cPtr, false);
  }

  public void setLookup_service_finish(SWIGTYPE_p_f_p_GResolver_p_GAsyncResult_p_p_GError__p__GList value) {
    fridacoreJNI._GResolverClass_lookup_service_finish_set(swigCPtr, this, SWIGTYPE_p_f_p_GResolver_p_GAsyncResult_p_p_GError__p__GList.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_GResolver_p_GAsyncResult_p_p_GError__p__GList getLookup_service_finish() {
    long cPtr = fridacoreJNI._GResolverClass_lookup_service_finish_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_GResolver_p_GAsyncResult_p_p_GError__p__GList(cPtr, false);
  }

  public void setLookup_records(SWIGTYPE_p_f_p_GResolver_p_q_const__gchar_GResolverRecordType_p_GCancellable_p_p_GError__p__GList value) {
    fridacoreJNI._GResolverClass_lookup_records_set(swigCPtr, this, SWIGTYPE_p_f_p_GResolver_p_q_const__gchar_GResolverRecordType_p_GCancellable_p_p_GError__p__GList.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_GResolver_p_q_const__gchar_GResolverRecordType_p_GCancellable_p_p_GError__p__GList getLookup_records() {
    long cPtr = fridacoreJNI._GResolverClass_lookup_records_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_GResolver_p_q_const__gchar_GResolverRecordType_p_GCancellable_p_p_GError__p__GList(cPtr, false);
  }

  public void setLookup_records_async(SWIGTYPE_p_f_p__GResolver_p_q_const__char_enum_GResolverRecordType_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void value) {
    fridacoreJNI._GResolverClass_lookup_records_async_set(swigCPtr, this, SWIGTYPE_p_f_p__GResolver_p_q_const__char_enum_GResolverRecordType_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GResolver_p_q_const__char_enum_GResolverRecordType_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void getLookup_records_async() {
    long cPtr = fridacoreJNI._GResolverClass_lookup_records_async_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GResolver_p_q_const__char_enum_GResolverRecordType_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void(cPtr, false);
  }

  public void setLookup_records_finish(SWIGTYPE_p_f_p_GResolver_p_GAsyncResult_p_p_GError__p__GList value) {
    fridacoreJNI._GResolverClass_lookup_records_finish_set(swigCPtr, this, SWIGTYPE_p_f_p_GResolver_p_GAsyncResult_p_p_GError__p__GList.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_GResolver_p_GAsyncResult_p_p_GError__p__GList getLookup_records_finish() {
    long cPtr = fridacoreJNI._GResolverClass_lookup_records_finish_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_GResolver_p_GAsyncResult_p_p_GError__p__GList(cPtr, false);
  }

  public void setLookup_by_name_with_flags_async(SWIGTYPE_p_f_p__GResolver_p_q_const__char_enum_GResolverNameLookupFlags_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void value) {
    fridacoreJNI._GResolverClass_lookup_by_name_with_flags_async_set(swigCPtr, this, SWIGTYPE_p_f_p__GResolver_p_q_const__char_enum_GResolverNameLookupFlags_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GResolver_p_q_const__char_enum_GResolverNameLookupFlags_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void getLookup_by_name_with_flags_async() {
    long cPtr = fridacoreJNI._GResolverClass_lookup_by_name_with_flags_async_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GResolver_p_q_const__char_enum_GResolverNameLookupFlags_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void(cPtr, false);
  }

  public void setLookup_by_name_with_flags_finish(SWIGTYPE_p_f_p_GResolver_p_GAsyncResult_p_p_GError__p__GList value) {
    fridacoreJNI._GResolverClass_lookup_by_name_with_flags_finish_set(swigCPtr, this, SWIGTYPE_p_f_p_GResolver_p_GAsyncResult_p_p_GError__p__GList.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_GResolver_p_GAsyncResult_p_p_GError__p__GList getLookup_by_name_with_flags_finish() {
    long cPtr = fridacoreJNI._GResolverClass_lookup_by_name_with_flags_finish_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_GResolver_p_GAsyncResult_p_p_GError__p__GList(cPtr, false);
  }

  public void setLookup_by_name_with_flags(SWIGTYPE_p_f_p_GResolver_p_q_const__gchar_GResolverNameLookupFlags_p_GCancellable_p_p_GError__p__GList value) {
    fridacoreJNI._GResolverClass_lookup_by_name_with_flags_set(swigCPtr, this, SWIGTYPE_p_f_p_GResolver_p_q_const__gchar_GResolverNameLookupFlags_p_GCancellable_p_p_GError__p__GList.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_GResolver_p_q_const__gchar_GResolverNameLookupFlags_p_GCancellable_p_p_GError__p__GList getLookup_by_name_with_flags() {
    long cPtr = fridacoreJNI._GResolverClass_lookup_by_name_with_flags_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_GResolver_p_q_const__gchar_GResolverNameLookupFlags_p_GCancellable_p_p_GError__p__GList(cPtr, false);
  }

  public _GResolverClass() {
    this(fridacoreJNI.new__GResolverClass(), true);
  }

}
