/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public class _GScannerConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GScannerConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GScannerConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fridacoreJNI.delete__GScannerConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCset_skip_characters(String value) {
    fridacoreJNI._GScannerConfig_cset_skip_characters_set(swigCPtr, this, value);
  }

  public String getCset_skip_characters() {
    return fridacoreJNI._GScannerConfig_cset_skip_characters_get(swigCPtr, this);
  }

  public void setCset_identifier_first(String value) {
    fridacoreJNI._GScannerConfig_cset_identifier_first_set(swigCPtr, this, value);
  }

  public String getCset_identifier_first() {
    return fridacoreJNI._GScannerConfig_cset_identifier_first_get(swigCPtr, this);
  }

  public void setCset_identifier_nth(String value) {
    fridacoreJNI._GScannerConfig_cset_identifier_nth_set(swigCPtr, this, value);
  }

  public String getCset_identifier_nth() {
    return fridacoreJNI._GScannerConfig_cset_identifier_nth_get(swigCPtr, this);
  }

  public void setCpair_comment_single(String value) {
    fridacoreJNI._GScannerConfig_cpair_comment_single_set(swigCPtr, this, value);
  }

  public String getCpair_comment_single() {
    return fridacoreJNI._GScannerConfig_cpair_comment_single_get(swigCPtr, this);
  }

  public void setCase_sensitive(long value) {
    fridacoreJNI._GScannerConfig_case_sensitive_set(swigCPtr, this, value);
  }

  public long getCase_sensitive() {
    return fridacoreJNI._GScannerConfig_case_sensitive_get(swigCPtr, this);
  }

  public void setSkip_comment_multi(long value) {
    fridacoreJNI._GScannerConfig_skip_comment_multi_set(swigCPtr, this, value);
  }

  public long getSkip_comment_multi() {
    return fridacoreJNI._GScannerConfig_skip_comment_multi_get(swigCPtr, this);
  }

  public void setSkip_comment_single(long value) {
    fridacoreJNI._GScannerConfig_skip_comment_single_set(swigCPtr, this, value);
  }

  public long getSkip_comment_single() {
    return fridacoreJNI._GScannerConfig_skip_comment_single_get(swigCPtr, this);
  }

  public void setScan_comment_multi(long value) {
    fridacoreJNI._GScannerConfig_scan_comment_multi_set(swigCPtr, this, value);
  }

  public long getScan_comment_multi() {
    return fridacoreJNI._GScannerConfig_scan_comment_multi_get(swigCPtr, this);
  }

  public void setScan_identifier(long value) {
    fridacoreJNI._GScannerConfig_scan_identifier_set(swigCPtr, this, value);
  }

  public long getScan_identifier() {
    return fridacoreJNI._GScannerConfig_scan_identifier_get(swigCPtr, this);
  }

  public void setScan_identifier_1char(long value) {
    fridacoreJNI._GScannerConfig_scan_identifier_1char_set(swigCPtr, this, value);
  }

  public long getScan_identifier_1char() {
    return fridacoreJNI._GScannerConfig_scan_identifier_1char_get(swigCPtr, this);
  }

  public void setScan_identifier_NULL(long value) {
    fridacoreJNI._GScannerConfig_scan_identifier_NULL_set(swigCPtr, this, value);
  }

  public long getScan_identifier_NULL() {
    return fridacoreJNI._GScannerConfig_scan_identifier_NULL_get(swigCPtr, this);
  }

  public void setScan_symbols(long value) {
    fridacoreJNI._GScannerConfig_scan_symbols_set(swigCPtr, this, value);
  }

  public long getScan_symbols() {
    return fridacoreJNI._GScannerConfig_scan_symbols_get(swigCPtr, this);
  }

  public void setScan_binary(long value) {
    fridacoreJNI._GScannerConfig_scan_binary_set(swigCPtr, this, value);
  }

  public long getScan_binary() {
    return fridacoreJNI._GScannerConfig_scan_binary_get(swigCPtr, this);
  }

  public void setScan_octal(long value) {
    fridacoreJNI._GScannerConfig_scan_octal_set(swigCPtr, this, value);
  }

  public long getScan_octal() {
    return fridacoreJNI._GScannerConfig_scan_octal_get(swigCPtr, this);
  }

  public void setScan_float(long value) {
    fridacoreJNI._GScannerConfig_scan_float_set(swigCPtr, this, value);
  }

  public long getScan_float() {
    return fridacoreJNI._GScannerConfig_scan_float_get(swigCPtr, this);
  }

  public void setScan_hex(long value) {
    fridacoreJNI._GScannerConfig_scan_hex_set(swigCPtr, this, value);
  }

  public long getScan_hex() {
    return fridacoreJNI._GScannerConfig_scan_hex_get(swigCPtr, this);
  }

  public void setScan_hex_dollar(long value) {
    fridacoreJNI._GScannerConfig_scan_hex_dollar_set(swigCPtr, this, value);
  }

  public long getScan_hex_dollar() {
    return fridacoreJNI._GScannerConfig_scan_hex_dollar_get(swigCPtr, this);
  }

  public void setScan_string_sq(long value) {
    fridacoreJNI._GScannerConfig_scan_string_sq_set(swigCPtr, this, value);
  }

  public long getScan_string_sq() {
    return fridacoreJNI._GScannerConfig_scan_string_sq_get(swigCPtr, this);
  }

  public void setScan_string_dq(long value) {
    fridacoreJNI._GScannerConfig_scan_string_dq_set(swigCPtr, this, value);
  }

  public long getScan_string_dq() {
    return fridacoreJNI._GScannerConfig_scan_string_dq_get(swigCPtr, this);
  }

  public void setNumbers_2_int(long value) {
    fridacoreJNI._GScannerConfig_numbers_2_int_set(swigCPtr, this, value);
  }

  public long getNumbers_2_int() {
    return fridacoreJNI._GScannerConfig_numbers_2_int_get(swigCPtr, this);
  }

  public void setInt_2_float(long value) {
    fridacoreJNI._GScannerConfig_int_2_float_set(swigCPtr, this, value);
  }

  public long getInt_2_float() {
    return fridacoreJNI._GScannerConfig_int_2_float_get(swigCPtr, this);
  }

  public void setIdentifier_2_string(long value) {
    fridacoreJNI._GScannerConfig_identifier_2_string_set(swigCPtr, this, value);
  }

  public long getIdentifier_2_string() {
    return fridacoreJNI._GScannerConfig_identifier_2_string_get(swigCPtr, this);
  }

  public void setChar_2_token(long value) {
    fridacoreJNI._GScannerConfig_char_2_token_set(swigCPtr, this, value);
  }

  public long getChar_2_token() {
    return fridacoreJNI._GScannerConfig_char_2_token_get(swigCPtr, this);
  }

  public void setSymbol_2_token(long value) {
    fridacoreJNI._GScannerConfig_symbol_2_token_set(swigCPtr, this, value);
  }

  public long getSymbol_2_token() {
    return fridacoreJNI._GScannerConfig_symbol_2_token_get(swigCPtr, this);
  }

  public void setScope_0_fallback(long value) {
    fridacoreJNI._GScannerConfig_scope_0_fallback_set(swigCPtr, this, value);
  }

  public long getScope_0_fallback() {
    return fridacoreJNI._GScannerConfig_scope_0_fallback_get(swigCPtr, this);
  }

  public void setStore_int64(long value) {
    fridacoreJNI._GScannerConfig_store_int64_set(swigCPtr, this, value);
  }

  public long getStore_int64() {
    return fridacoreJNI._GScannerConfig_store_int64_get(swigCPtr, this);
  }

  public void setPadding_dummy(long value) {
    fridacoreJNI._GScannerConfig_padding_dummy_set(swigCPtr, this, value);
  }

  public long getPadding_dummy() {
    return fridacoreJNI._GScannerConfig_padding_dummy_get(swigCPtr, this);
  }

  public _GScannerConfig() {
    this(fridacoreJNI.new__GScannerConfig(), true);
  }

}
