/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public class _GSignalInvocationHint {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GSignalInvocationHint(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GSignalInvocationHint obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fridacoreJNI.delete__GSignalInvocationHint(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSignal_id(long value) {
    fridacoreJNI._GSignalInvocationHint_signal_id_set(swigCPtr, this, value);
  }

  public long getSignal_id() {
    return fridacoreJNI._GSignalInvocationHint_signal_id_get(swigCPtr, this);
  }

  public void setDetail(long value) {
    fridacoreJNI._GSignalInvocationHint_detail_set(swigCPtr, this, value);
  }

  public long getDetail() {
    return fridacoreJNI._GSignalInvocationHint_detail_get(swigCPtr, this);
  }

  public void setRun_type(GSignalFlags value) {
    fridacoreJNI._GSignalInvocationHint_run_type_set(swigCPtr, this, value.swigValue());
  }

  public GSignalFlags getRun_type() {
    return GSignalFlags.swigToEnum(fridacoreJNI._GSignalInvocationHint_run_type_get(swigCPtr, this));
  }

  public _GSignalInvocationHint() {
    this(fridacoreJNI.new__GSignalInvocationHint(), true);
  }

}
