/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public class _GSocketService {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GSocketService(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GSocketService obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fridacoreJNI.delete__GSocketService(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setParent_instance(_GSocketListener value) {
    fridacoreJNI._GSocketService_parent_instance_set(swigCPtr, this, _GSocketListener.getCPtr(value), value);
  }

  public _GSocketListener getParent_instance() {
    long cPtr = fridacoreJNI._GSocketService_parent_instance_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GSocketListener(cPtr, false);
  }

  public void setPriv(SWIGTYPE_p__GSocketServicePrivate value) {
    fridacoreJNI._GSocketService_priv_set(swigCPtr, this, SWIGTYPE_p__GSocketServicePrivate.getCPtr(value));
  }

  public SWIGTYPE_p__GSocketServicePrivate getPriv() {
    long cPtr = fridacoreJNI._GSocketService_priv_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p__GSocketServicePrivate(cPtr, false);
  }

  public _GSocketService() {
    this(fridacoreJNI.new__GSocketService(), true);
  }

}
