/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public class _GSocketAddressClass {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GSocketAddressClass(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GSocketAddressClass obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fridacoreJNI.delete__GSocketAddressClass(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setParent_class(_GObjectClass value) {
    fridacoreJNI._GSocketAddressClass_parent_class_set(swigCPtr, this, _GObjectClass.getCPtr(value), value);
  }

  public _GObjectClass getParent_class() {
    long cPtr = fridacoreJNI._GSocketAddressClass_parent_class_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GObjectClass(cPtr, false);
  }

  public void setGet_family(SWIGTYPE_p_f_p__GSocketAddress__GSocketFamily value) {
    fridacoreJNI._GSocketAddressClass_get_family_set(swigCPtr, this, SWIGTYPE_p_f_p__GSocketAddress__GSocketFamily.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GSocketAddress__GSocketFamily getGet_family() {
    long cPtr = fridacoreJNI._GSocketAddressClass_get_family_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GSocketAddress__GSocketFamily(cPtr, false);
  }

  public void setGet_native_size(SWIGTYPE_p_f_p__GSocketAddress__long value) {
    fridacoreJNI._GSocketAddressClass_get_native_size_set(swigCPtr, this, SWIGTYPE_p_f_p__GSocketAddress__long.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GSocketAddress__long getGet_native_size() {
    long cPtr = fridacoreJNI._GSocketAddressClass_get_native_size_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GSocketAddress__long(cPtr, false);
  }

  public void setTo_native(SWIGTYPE_p_f_p__GSocketAddress_p_void_unsigned_long_p_p__GError__int value) {
    fridacoreJNI._GSocketAddressClass_to_native_set(swigCPtr, this, SWIGTYPE_p_f_p__GSocketAddress_p_void_unsigned_long_p_p__GError__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GSocketAddress_p_void_unsigned_long_p_p__GError__int getTo_native() {
    long cPtr = fridacoreJNI._GSocketAddressClass_to_native_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GSocketAddress_p_void_unsigned_long_p_p__GError__int(cPtr, false);
  }

  public _GSocketAddressClass() {
    this(fridacoreJNI.new__GSocketAddressClass(), true);
  }

}
