/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public class _GStaticResource {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GStaticResource(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GStaticResource obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fridacoreJNI.delete__GStaticResource(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setData(SWIGTYPE_p_unsigned_char value) {
    fridacoreJNI._GStaticResource_data_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getData() {
    long cPtr = fridacoreJNI._GStaticResource_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setData_len(long value) {
    fridacoreJNI._GStaticResource_data_len_set(swigCPtr, this, value);
  }

  public long getData_len() {
    return fridacoreJNI._GStaticResource_data_len_get(swigCPtr, this);
  }

  public void setResource(SWIGTYPE_p__GResource value) {
    fridacoreJNI._GStaticResource_resource_set(swigCPtr, this, SWIGTYPE_p__GResource.getCPtr(value));
  }

  public SWIGTYPE_p__GResource getResource() {
    long cPtr = fridacoreJNI._GStaticResource_resource_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p__GResource(cPtr, false);
  }

  public void setNext(_GStaticResource value) {
    fridacoreJNI._GStaticResource_next_set(swigCPtr, this, _GStaticResource.getCPtr(value), value);
  }

  public _GStaticResource getNext() {
    long cPtr = fridacoreJNI._GStaticResource_next_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GStaticResource(cPtr, false);
  }

  public void setPadding(SWIGTYPE_p_void value) {
    fridacoreJNI._GStaticResource_padding_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getPadding() {
    long cPtr = fridacoreJNI._GStaticResource_padding_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public _GStaticResource() {
    this(fridacoreJNI.new__GStaticResource(), true);
  }

}
