/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public class _GThreadFunctions {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GThreadFunctions(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GThreadFunctions obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fridacoreJNI.delete__GThreadFunctions(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMutex_new(SWIGTYPE_p_f_void__p__GMutex value) {
    fridacoreJNI._GThreadFunctions_mutex_new_set(swigCPtr, this, SWIGTYPE_p_f_void__p__GMutex.getCPtr(value));
  }

  public SWIGTYPE_p_f_void__p__GMutex getMutex_new() {
    long cPtr = fridacoreJNI._GThreadFunctions_mutex_new_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_void__p__GMutex(cPtr, false);
  }

  public void setMutex_lock(SWIGTYPE_p_f_p__GMutex__void value) {
    fridacoreJNI._GThreadFunctions_mutex_lock_set(swigCPtr, this, SWIGTYPE_p_f_p__GMutex__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GMutex__void getMutex_lock() {
    long cPtr = fridacoreJNI._GThreadFunctions_mutex_lock_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GMutex__void(cPtr, false);
  }

  public void setMutex_trylock(SWIGTYPE_p_f_p__GMutex__int value) {
    fridacoreJNI._GThreadFunctions_mutex_trylock_set(swigCPtr, this, SWIGTYPE_p_f_p__GMutex__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GMutex__int getMutex_trylock() {
    long cPtr = fridacoreJNI._GThreadFunctions_mutex_trylock_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GMutex__int(cPtr, false);
  }

  public void setMutex_unlock(SWIGTYPE_p_f_p__GMutex__void value) {
    fridacoreJNI._GThreadFunctions_mutex_unlock_set(swigCPtr, this, SWIGTYPE_p_f_p__GMutex__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GMutex__void getMutex_unlock() {
    long cPtr = fridacoreJNI._GThreadFunctions_mutex_unlock_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GMutex__void(cPtr, false);
  }

  public void setMutex_free(SWIGTYPE_p_f_p__GMutex__void value) {
    fridacoreJNI._GThreadFunctions_mutex_free_set(swigCPtr, this, SWIGTYPE_p_f_p__GMutex__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GMutex__void getMutex_free() {
    long cPtr = fridacoreJNI._GThreadFunctions_mutex_free_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GMutex__void(cPtr, false);
  }

  public void setCond_new(SWIGTYPE_p_f_void__p__GCond value) {
    fridacoreJNI._GThreadFunctions_cond_new_set(swigCPtr, this, SWIGTYPE_p_f_void__p__GCond.getCPtr(value));
  }

  public SWIGTYPE_p_f_void__p__GCond getCond_new() {
    long cPtr = fridacoreJNI._GThreadFunctions_cond_new_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_void__p__GCond(cPtr, false);
  }

  public void setCond_signal(SWIGTYPE_p_f_p__GCond__void value) {
    fridacoreJNI._GThreadFunctions_cond_signal_set(swigCPtr, this, SWIGTYPE_p_f_p__GCond__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GCond__void getCond_signal() {
    long cPtr = fridacoreJNI._GThreadFunctions_cond_signal_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GCond__void(cPtr, false);
  }

  public void setCond_broadcast(SWIGTYPE_p_f_p__GCond__void value) {
    fridacoreJNI._GThreadFunctions_cond_broadcast_set(swigCPtr, this, SWIGTYPE_p_f_p__GCond__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GCond__void getCond_broadcast() {
    long cPtr = fridacoreJNI._GThreadFunctions_cond_broadcast_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GCond__void(cPtr, false);
  }

  public void setCond_wait(SWIGTYPE_p_f_p__GCond_p__GMutex__void value) {
    fridacoreJNI._GThreadFunctions_cond_wait_set(swigCPtr, this, SWIGTYPE_p_f_p__GCond_p__GMutex__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GCond_p__GMutex__void getCond_wait() {
    long cPtr = fridacoreJNI._GThreadFunctions_cond_wait_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GCond_p__GMutex__void(cPtr, false);
  }

  public void setCond_timed_wait(SWIGTYPE_p_f_p__GCond_p__GMutex_p__GTimeVal__int value) {
    fridacoreJNI._GThreadFunctions_cond_timed_wait_set(swigCPtr, this, SWIGTYPE_p_f_p__GCond_p__GMutex_p__GTimeVal__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GCond_p__GMutex_p__GTimeVal__int getCond_timed_wait() {
    long cPtr = fridacoreJNI._GThreadFunctions_cond_timed_wait_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GCond_p__GMutex_p__GTimeVal__int(cPtr, false);
  }

  public void setCond_free(SWIGTYPE_p_f_p__GCond__void value) {
    fridacoreJNI._GThreadFunctions_cond_free_set(swigCPtr, this, SWIGTYPE_p_f_p__GCond__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GCond__void getCond_free() {
    long cPtr = fridacoreJNI._GThreadFunctions_cond_free_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GCond__void(cPtr, false);
  }

  public void setPrivate_new(SWIGTYPE_p_f_GDestroyNotify__p__GPrivate value) {
    fridacoreJNI._GThreadFunctions_private_new_set(swigCPtr, this, SWIGTYPE_p_f_GDestroyNotify__p__GPrivate.getCPtr(value));
  }

  public SWIGTYPE_p_f_GDestroyNotify__p__GPrivate getPrivate_new() {
    long cPtr = fridacoreJNI._GThreadFunctions_private_new_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_GDestroyNotify__p__GPrivate(cPtr, false);
  }

  public void setPrivate_get(SWIGTYPE_p_f_p__GPrivate__p_void value) {
    fridacoreJNI._GThreadFunctions_private_get_set(swigCPtr, this, SWIGTYPE_p_f_p__GPrivate__p_void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GPrivate__p_void getPrivate_get() {
    long cPtr = fridacoreJNI._GThreadFunctions_private_get_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GPrivate__p_void(cPtr, false);
  }

  public void setPrivate_set(SWIGTYPE_p_f_p__GPrivate_p_void__void value) {
    fridacoreJNI._GThreadFunctions_private_set_set(swigCPtr, this, SWIGTYPE_p_f_p__GPrivate_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GPrivate_p_void__void getPrivate_set() {
    long cPtr = fridacoreJNI._GThreadFunctions_private_set_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GPrivate_p_void__void(cPtr, false);
  }

  public void setThread_create(SWIGTYPE_p_f_p_f_p_void__p_void_p_void_unsigned_long_int_int_enum_GThreadPriority_p_void_p_p__GError__void value) {
    fridacoreJNI._GThreadFunctions_thread_create_set(swigCPtr, this, SWIGTYPE_p_f_p_f_p_void__p_void_p_void_unsigned_long_int_int_enum_GThreadPriority_p_void_p_p__GError__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_f_p_void__p_void_p_void_unsigned_long_int_int_enum_GThreadPriority_p_void_p_p__GError__void getThread_create() {
    long cPtr = fridacoreJNI._GThreadFunctions_thread_create_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_f_p_void__p_void_p_void_unsigned_long_int_int_enum_GThreadPriority_p_void_p_p__GError__void(cPtr, false);
  }

  public void setThread_yield(SWIGTYPE_p_f_void__void value) {
    fridacoreJNI._GThreadFunctions_thread_yield_set(swigCPtr, this, SWIGTYPE_p_f_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_void__void getThread_yield() {
    long cPtr = fridacoreJNI._GThreadFunctions_thread_yield_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_void__void(cPtr, false);
  }

  public void setThread_join(SWIGTYPE_p_f_p_void__void value) {
    fridacoreJNI._GThreadFunctions_thread_join_set(swigCPtr, this, SWIGTYPE_p_f_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void__void getThread_join() {
    long cPtr = fridacoreJNI._GThreadFunctions_thread_join_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void__void(cPtr, false);
  }

  public void setThread_exit(SWIGTYPE_p_f_void__void value) {
    fridacoreJNI._GThreadFunctions_thread_exit_set(swigCPtr, this, SWIGTYPE_p_f_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_void__void getThread_exit() {
    long cPtr = fridacoreJNI._GThreadFunctions_thread_exit_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_void__void(cPtr, false);
  }

  public void setThread_set_priority(SWIGTYPE_p_f_p_void_enum_GThreadPriority__void value) {
    fridacoreJNI._GThreadFunctions_thread_set_priority_set(swigCPtr, this, SWIGTYPE_p_f_p_void_enum_GThreadPriority__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void_enum_GThreadPriority__void getThread_set_priority() {
    long cPtr = fridacoreJNI._GThreadFunctions_thread_set_priority_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void_enum_GThreadPriority__void(cPtr, false);
  }

  public void setThread_self(SWIGTYPE_p_f_p_void__void value) {
    fridacoreJNI._GThreadFunctions_thread_self_set(swigCPtr, this, SWIGTYPE_p_f_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void__void getThread_self() {
    long cPtr = fridacoreJNI._GThreadFunctions_thread_self_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void__void(cPtr, false);
  }

  public void setThread_equal(SWIGTYPE_p_f_p_void_p_void__int value) {
    fridacoreJNI._GThreadFunctions_thread_equal_set(swigCPtr, this, SWIGTYPE_p_f_p_void_p_void__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void_p_void__int getThread_equal() {
    long cPtr = fridacoreJNI._GThreadFunctions_thread_equal_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void_p_void__int(cPtr, false);
  }

  public _GThreadFunctions() {
    this(fridacoreJNI.new__GThreadFunctions(), true);
  }

}
