/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public class _GThreadCallbacks {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GThreadCallbacks(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GThreadCallbacks obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fridacoreJNI.delete__GThreadCallbacks(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setOn_thread_init(SWIGTYPE_p_f_void__void value) {
    fridacoreJNI._GThreadCallbacks_on_thread_init_set(swigCPtr, this, SWIGTYPE_p_f_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_void__void getOn_thread_init() {
    long cPtr = fridacoreJNI._GThreadCallbacks_on_thread_init_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_void__void(cPtr, false);
  }

  public void setOn_thread_realize(SWIGTYPE_p_f_void__void value) {
    fridacoreJNI._GThreadCallbacks_on_thread_realize_set(swigCPtr, this, SWIGTYPE_p_f_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_void__void getOn_thread_realize() {
    long cPtr = fridacoreJNI._GThreadCallbacks_on_thread_realize_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_void__void(cPtr, false);
  }

  public void setOn_thread_dispose(SWIGTYPE_p_f_void__void value) {
    fridacoreJNI._GThreadCallbacks_on_thread_dispose_set(swigCPtr, this, SWIGTYPE_p_f_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_void__void getOn_thread_dispose() {
    long cPtr = fridacoreJNI._GThreadCallbacks_on_thread_dispose_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_void__void(cPtr, false);
  }

  public void setOn_thread_finalize(SWIGTYPE_p_f_void__void value) {
    fridacoreJNI._GThreadCallbacks_on_thread_finalize_set(swigCPtr, this, SWIGTYPE_p_f_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_void__void getOn_thread_finalize() {
    long cPtr = fridacoreJNI._GThreadCallbacks_on_thread_finalize_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_void__void(cPtr, false);
  }

  public _GThreadCallbacks() {
    this(fridacoreJNI.new__GThreadCallbacks(), true);
  }

}
