/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public class _GTlsInteractionClass {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GTlsInteractionClass(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GTlsInteractionClass obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fridacoreJNI.delete__GTlsInteractionClass(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setParent_class(_GObjectClass value) {
    fridacoreJNI._GTlsInteractionClass_parent_class_set(swigCPtr, this, _GObjectClass.getCPtr(value), value);
  }

  public _GObjectClass getParent_class() {
    long cPtr = fridacoreJNI._GTlsInteractionClass_parent_class_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GObjectClass(cPtr, false);
  }

  public void setAsk_password(SWIGTYPE_p_f_p__GTlsInteraction_p__GTlsPassword_p__GCancellable_p_p__GError__GTlsInteractionResult value) {
    fridacoreJNI._GTlsInteractionClass_ask_password_set(swigCPtr, this, SWIGTYPE_p_f_p__GTlsInteraction_p__GTlsPassword_p__GCancellable_p_p__GError__GTlsInteractionResult.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GTlsInteraction_p__GTlsPassword_p__GCancellable_p_p__GError__GTlsInteractionResult getAsk_password() {
    long cPtr = fridacoreJNI._GTlsInteractionClass_ask_password_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GTlsInteraction_p__GTlsPassword_p__GCancellable_p_p__GError__GTlsInteractionResult(cPtr, false);
  }

  public void setAsk_password_async(SWIGTYPE_p_f_p__GTlsInteraction_p__GTlsPassword_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void value) {
    fridacoreJNI._GTlsInteractionClass_ask_password_async_set(swigCPtr, this, SWIGTYPE_p_f_p__GTlsInteraction_p__GTlsPassword_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GTlsInteraction_p__GTlsPassword_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void getAsk_password_async() {
    long cPtr = fridacoreJNI._GTlsInteractionClass_ask_password_async_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GTlsInteraction_p__GTlsPassword_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void(cPtr, false);
  }

  public void setAsk_password_finish(SWIGTYPE_p_f_p__GTlsInteraction_p__GAsyncResult_p_p__GError__GTlsInteractionResult value) {
    fridacoreJNI._GTlsInteractionClass_ask_password_finish_set(swigCPtr, this, SWIGTYPE_p_f_p__GTlsInteraction_p__GAsyncResult_p_p__GError__GTlsInteractionResult.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GTlsInteraction_p__GAsyncResult_p_p__GError__GTlsInteractionResult getAsk_password_finish() {
    long cPtr = fridacoreJNI._GTlsInteractionClass_ask_password_finish_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GTlsInteraction_p__GAsyncResult_p_p__GError__GTlsInteractionResult(cPtr, false);
  }

  public void setRequest_certificate(SWIGTYPE_p_f_p__GTlsInteraction_p__GTlsConnection_enum_GTlsCertificateRequestFlags_p__GCancellable_p_p__GError__GTlsInteractionResult value) {
    fridacoreJNI._GTlsInteractionClass_request_certificate_set(swigCPtr, this, SWIGTYPE_p_f_p__GTlsInteraction_p__GTlsConnection_enum_GTlsCertificateRequestFlags_p__GCancellable_p_p__GError__GTlsInteractionResult.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GTlsInteraction_p__GTlsConnection_enum_GTlsCertificateRequestFlags_p__GCancellable_p_p__GError__GTlsInteractionResult getRequest_certificate() {
    long cPtr = fridacoreJNI._GTlsInteractionClass_request_certificate_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GTlsInteraction_p__GTlsConnection_enum_GTlsCertificateRequestFlags_p__GCancellable_p_p__GError__GTlsInteractionResult(cPtr, false);
  }

  public void setRequest_certificate_async(SWIGTYPE_p_f_p__GTlsInteraction_p__GTlsConnection_enum_GTlsCertificateRequestFlags_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void value) {
    fridacoreJNI._GTlsInteractionClass_request_certificate_async_set(swigCPtr, this, SWIGTYPE_p_f_p__GTlsInteraction_p__GTlsConnection_enum_GTlsCertificateRequestFlags_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GTlsInteraction_p__GTlsConnection_enum_GTlsCertificateRequestFlags_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void getRequest_certificate_async() {
    long cPtr = fridacoreJNI._GTlsInteractionClass_request_certificate_async_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GTlsInteraction_p__GTlsConnection_enum_GTlsCertificateRequestFlags_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void(cPtr, false);
  }

  public void setRequest_certificate_finish(SWIGTYPE_p_f_p__GTlsInteraction_p__GAsyncResult_p_p__GError__GTlsInteractionResult value) {
    fridacoreJNI._GTlsInteractionClass_request_certificate_finish_set(swigCPtr, this, SWIGTYPE_p_f_p__GTlsInteraction_p__GAsyncResult_p_p__GError__GTlsInteractionResult.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GTlsInteraction_p__GAsyncResult_p_p__GError__GTlsInteractionResult getRequest_certificate_finish() {
    long cPtr = fridacoreJNI._GTlsInteractionClass_request_certificate_finish_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GTlsInteraction_p__GAsyncResult_p_p__GError__GTlsInteractionResult(cPtr, false);
  }

  public void setPadding(SWIGTYPE_p_p_void value) {
    fridacoreJNI._GTlsInteractionClass_padding_set(swigCPtr, this, SWIGTYPE_p_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_p_void getPadding() {
    long cPtr = fridacoreJNI._GTlsInteractionClass_padding_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_void(cPtr, false);
  }

  public _GTlsInteractionClass() {
    this(fridacoreJNI.new__GTlsInteractionClass(), true);
  }

}
