/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public class _GTlsBackendInterface {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GTlsBackendInterface(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GTlsBackendInterface obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fridacoreJNI.delete__GTlsBackendInterface(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setG_iface(_GTypeInterface value) {
    fridacoreJNI._GTlsBackendInterface_g_iface_set(swigCPtr, this, _GTypeInterface.getCPtr(value), value);
  }

  public _GTypeInterface getG_iface() {
    long cPtr = fridacoreJNI._GTlsBackendInterface_g_iface_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GTypeInterface(cPtr, false);
  }

  public void setSupports_tls(SWIGTYPE_p_f_p__GTlsBackend__int value) {
    fridacoreJNI._GTlsBackendInterface_supports_tls_set(swigCPtr, this, SWIGTYPE_p_f_p__GTlsBackend__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GTlsBackend__int getSupports_tls() {
    long cPtr = fridacoreJNI._GTlsBackendInterface_supports_tls_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GTlsBackend__int(cPtr, false);
  }

  public void setGet_certificate_type(SWIGTYPE_p_f_void__unsigned_long value) {
    fridacoreJNI._GTlsBackendInterface_get_certificate_type_set(swigCPtr, this, SWIGTYPE_p_f_void__unsigned_long.getCPtr(value));
  }

  public SWIGTYPE_p_f_void__unsigned_long getGet_certificate_type() {
    long cPtr = fridacoreJNI._GTlsBackendInterface_get_certificate_type_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_void__unsigned_long(cPtr, false);
  }

  public void setGet_client_connection_type(SWIGTYPE_p_f_void__unsigned_long value) {
    fridacoreJNI._GTlsBackendInterface_get_client_connection_type_set(swigCPtr, this, SWIGTYPE_p_f_void__unsigned_long.getCPtr(value));
  }

  public SWIGTYPE_p_f_void__unsigned_long getGet_client_connection_type() {
    long cPtr = fridacoreJNI._GTlsBackendInterface_get_client_connection_type_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_void__unsigned_long(cPtr, false);
  }

  public void setGet_server_connection_type(SWIGTYPE_p_f_void__unsigned_long value) {
    fridacoreJNI._GTlsBackendInterface_get_server_connection_type_set(swigCPtr, this, SWIGTYPE_p_f_void__unsigned_long.getCPtr(value));
  }

  public SWIGTYPE_p_f_void__unsigned_long getGet_server_connection_type() {
    long cPtr = fridacoreJNI._GTlsBackendInterface_get_server_connection_type_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_void__unsigned_long(cPtr, false);
  }

  public void setGet_file_database_type(SWIGTYPE_p_f_void__unsigned_long value) {
    fridacoreJNI._GTlsBackendInterface_get_file_database_type_set(swigCPtr, this, SWIGTYPE_p_f_void__unsigned_long.getCPtr(value));
  }

  public SWIGTYPE_p_f_void__unsigned_long getGet_file_database_type() {
    long cPtr = fridacoreJNI._GTlsBackendInterface_get_file_database_type_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_void__unsigned_long(cPtr, false);
  }

  public void setGet_default_database(SWIGTYPE_p_f_p_GTlsBackend__p__GTlsDatabase value) {
    fridacoreJNI._GTlsBackendInterface_get_default_database_set(swigCPtr, this, SWIGTYPE_p_f_p_GTlsBackend__p__GTlsDatabase.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_GTlsBackend__p__GTlsDatabase getGet_default_database() {
    long cPtr = fridacoreJNI._GTlsBackendInterface_get_default_database_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_GTlsBackend__p__GTlsDatabase(cPtr, false);
  }

  public void setSupports_dtls(SWIGTYPE_p_f_p__GTlsBackend__int value) {
    fridacoreJNI._GTlsBackendInterface_supports_dtls_set(swigCPtr, this, SWIGTYPE_p_f_p__GTlsBackend__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GTlsBackend__int getSupports_dtls() {
    long cPtr = fridacoreJNI._GTlsBackendInterface_supports_dtls_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GTlsBackend__int(cPtr, false);
  }

  public void setGet_dtls_client_connection_type(SWIGTYPE_p_f_void__unsigned_long value) {
    fridacoreJNI._GTlsBackendInterface_get_dtls_client_connection_type_set(swigCPtr, this, SWIGTYPE_p_f_void__unsigned_long.getCPtr(value));
  }

  public SWIGTYPE_p_f_void__unsigned_long getGet_dtls_client_connection_type() {
    long cPtr = fridacoreJNI._GTlsBackendInterface_get_dtls_client_connection_type_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_void__unsigned_long(cPtr, false);
  }

  public void setGet_dtls_server_connection_type(SWIGTYPE_p_f_void__unsigned_long value) {
    fridacoreJNI._GTlsBackendInterface_get_dtls_server_connection_type_set(swigCPtr, this, SWIGTYPE_p_f_void__unsigned_long.getCPtr(value));
  }

  public SWIGTYPE_p_f_void__unsigned_long getGet_dtls_server_connection_type() {
    long cPtr = fridacoreJNI._GTlsBackendInterface_get_dtls_server_connection_type_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_void__unsigned_long(cPtr, false);
  }

  public _GTlsBackendInterface() {
    this(fridacoreJNI.new__GTlsBackendInterface(), true);
  }

}
