/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public class _GTlsConnection {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GTlsConnection(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GTlsConnection obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fridacoreJNI.delete__GTlsConnection(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setParent_instance(_GIOStream value) {
    fridacoreJNI._GTlsConnection_parent_instance_set(swigCPtr, this, _GIOStream.getCPtr(value), value);
  }

  public _GIOStream getParent_instance() {
    long cPtr = fridacoreJNI._GTlsConnection_parent_instance_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GIOStream(cPtr, false);
  }

  public void setPriv(SWIGTYPE_p__GTlsConnectionPrivate value) {
    fridacoreJNI._GTlsConnection_priv_set(swigCPtr, this, SWIGTYPE_p__GTlsConnectionPrivate.getCPtr(value));
  }

  public SWIGTYPE_p__GTlsConnectionPrivate getPriv() {
    long cPtr = fridacoreJNI._GTlsConnection_priv_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p__GTlsConnectionPrivate(cPtr, false);
  }

  public _GTlsConnection() {
    this(fridacoreJNI.new__GTlsConnection(), true);
  }

}
