/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public class _GVfsClass {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GVfsClass(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GVfsClass obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fridacoreJNI.delete__GVfsClass(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setParent_class(_GObjectClass value) {
    fridacoreJNI._GVfsClass_parent_class_set(swigCPtr, this, _GObjectClass.getCPtr(value), value);
  }

  public _GObjectClass getParent_class() {
    long cPtr = fridacoreJNI._GVfsClass_parent_class_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GObjectClass(cPtr, false);
  }

  public void setIs_active(SWIGTYPE_p_f_p__GVfs__int value) {
    fridacoreJNI._GVfsClass_is_active_set(swigCPtr, this, SWIGTYPE_p_f_p__GVfs__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GVfs__int getIs_active() {
    long cPtr = fridacoreJNI._GVfsClass_is_active_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GVfs__int(cPtr, false);
  }

  public void setGet_file_for_path(SWIGTYPE_p_f_p__GVfs_p_q_const__char__p__GFile value) {
    fridacoreJNI._GVfsClass_get_file_for_path_set(swigCPtr, this, SWIGTYPE_p_f_p__GVfs_p_q_const__char__p__GFile.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GVfs_p_q_const__char__p__GFile getGet_file_for_path() {
    long cPtr = fridacoreJNI._GVfsClass_get_file_for_path_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GVfs_p_q_const__char__p__GFile(cPtr, false);
  }

  public void setGet_file_for_uri(SWIGTYPE_p_f_p__GVfs_p_q_const__char__p__GFile value) {
    fridacoreJNI._GVfsClass_get_file_for_uri_set(swigCPtr, this, SWIGTYPE_p_f_p__GVfs_p_q_const__char__p__GFile.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GVfs_p_q_const__char__p__GFile getGet_file_for_uri() {
    long cPtr = fridacoreJNI._GVfsClass_get_file_for_uri_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GVfs_p_q_const__char__p__GFile(cPtr, false);
  }

  public void setGet_supported_uri_schemes(SWIGTYPE_p_f_p__GVfs__p_p_char value) {
    fridacoreJNI._GVfsClass_get_supported_uri_schemes_set(swigCPtr, this, SWIGTYPE_p_f_p__GVfs__p_p_char.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GVfs__p_p_char getGet_supported_uri_schemes() {
    long cPtr = fridacoreJNI._GVfsClass_get_supported_uri_schemes_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GVfs__p_p_char(cPtr, false);
  }

  public void setParse_name(SWIGTYPE_p_f_p__GVfs_p_q_const__char__p__GFile value) {
    fridacoreJNI._GVfsClass_parse_name_set(swigCPtr, this, SWIGTYPE_p_f_p__GVfs_p_q_const__char__p__GFile.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GVfs_p_q_const__char__p__GFile getParse_name() {
    long cPtr = fridacoreJNI._GVfsClass_parse_name_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GVfs_p_q_const__char__p__GFile(cPtr, false);
  }

  public void setLocal_file_add_info(SWIGTYPE_p_f_p__GVfs_p_q_const__char_unsigned_long_p__GFileAttributeMatcher_p__GFileInfo_p__GCancellable_p_p_void_p_p_f_p_void__void__void value) {
    fridacoreJNI._GVfsClass_local_file_add_info_set(swigCPtr, this, SWIGTYPE_p_f_p__GVfs_p_q_const__char_unsigned_long_p__GFileAttributeMatcher_p__GFileInfo_p__GCancellable_p_p_void_p_p_f_p_void__void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GVfs_p_q_const__char_unsigned_long_p__GFileAttributeMatcher_p__GFileInfo_p__GCancellable_p_p_void_p_p_f_p_void__void__void getLocal_file_add_info() {
    long cPtr = fridacoreJNI._GVfsClass_local_file_add_info_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GVfs_p_q_const__char_unsigned_long_p__GFileAttributeMatcher_p__GFileInfo_p__GCancellable_p_p_void_p_p_f_p_void__void__void(cPtr, false);
  }

  public void setAdd_writable_namespaces(SWIGTYPE_p_f_p__GVfs_p__GFileAttributeInfoList__void value) {
    fridacoreJNI._GVfsClass_add_writable_namespaces_set(swigCPtr, this, SWIGTYPE_p_f_p__GVfs_p__GFileAttributeInfoList__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GVfs_p__GFileAttributeInfoList__void getAdd_writable_namespaces() {
    long cPtr = fridacoreJNI._GVfsClass_add_writable_namespaces_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GVfs_p__GFileAttributeInfoList__void(cPtr, false);
  }

  public void setLocal_file_set_attributes(SWIGTYPE_p_f_p__GVfs_p_q_const__char_p__GFileInfo_enum_GFileQueryInfoFlags_p__GCancellable_p_p__GError__int value) {
    fridacoreJNI._GVfsClass_local_file_set_attributes_set(swigCPtr, this, SWIGTYPE_p_f_p__GVfs_p_q_const__char_p__GFileInfo_enum_GFileQueryInfoFlags_p__GCancellable_p_p__GError__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GVfs_p_q_const__char_p__GFileInfo_enum_GFileQueryInfoFlags_p__GCancellable_p_p__GError__int getLocal_file_set_attributes() {
    long cPtr = fridacoreJNI._GVfsClass_local_file_set_attributes_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GVfs_p_q_const__char_p__GFileInfo_enum_GFileQueryInfoFlags_p__GCancellable_p_p__GError__int(cPtr, false);
  }

  public void setLocal_file_removed(SWIGTYPE_p_f_p__GVfs_p_q_const__char__void value) {
    fridacoreJNI._GVfsClass_local_file_removed_set(swigCPtr, this, SWIGTYPE_p_f_p__GVfs_p_q_const__char__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GVfs_p_q_const__char__void getLocal_file_removed() {
    long cPtr = fridacoreJNI._GVfsClass_local_file_removed_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GVfs_p_q_const__char__void(cPtr, false);
  }

  public void setLocal_file_moved(SWIGTYPE_p_f_p__GVfs_p_q_const__char_p_q_const__char__void value) {
    fridacoreJNI._GVfsClass_local_file_moved_set(swigCPtr, this, SWIGTYPE_p_f_p__GVfs_p_q_const__char_p_q_const__char__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GVfs_p_q_const__char_p_q_const__char__void getLocal_file_moved() {
    long cPtr = fridacoreJNI._GVfsClass_local_file_moved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GVfs_p_q_const__char_p_q_const__char__void(cPtr, false);
  }

  public void setDeserialize_icon(SWIGTYPE_p_f_p__GVfs_p__GVariant__p__GIcon value) {
    fridacoreJNI._GVfsClass_deserialize_icon_set(swigCPtr, this, SWIGTYPE_p_f_p__GVfs_p__GVariant__p__GIcon.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GVfs_p__GVariant__p__GIcon getDeserialize_icon() {
    long cPtr = fridacoreJNI._GVfsClass_deserialize_icon_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GVfs_p__GVariant__p__GIcon(cPtr, false);
  }

  public void set_g_reserved1(SWIGTYPE_p_f_void__void value) {
    fridacoreJNI._GVfsClass__g_reserved1_set(swigCPtr, this, SWIGTYPE_p_f_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_void__void get_g_reserved1() {
    long cPtr = fridacoreJNI._GVfsClass__g_reserved1_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_void__void(cPtr, false);
  }

  public void set_g_reserved2(SWIGTYPE_p_f_void__void value) {
    fridacoreJNI._GVfsClass__g_reserved2_set(swigCPtr, this, SWIGTYPE_p_f_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_void__void get_g_reserved2() {
    long cPtr = fridacoreJNI._GVfsClass__g_reserved2_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_void__void(cPtr, false);
  }

  public void set_g_reserved3(SWIGTYPE_p_f_void__void value) {
    fridacoreJNI._GVfsClass__g_reserved3_set(swigCPtr, this, SWIGTYPE_p_f_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_void__void get_g_reserved3() {
    long cPtr = fridacoreJNI._GVfsClass__g_reserved3_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_void__void(cPtr, false);
  }

  public void set_g_reserved4(SWIGTYPE_p_f_void__void value) {
    fridacoreJNI._GVfsClass__g_reserved4_set(swigCPtr, this, SWIGTYPE_p_f_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_void__void get_g_reserved4() {
    long cPtr = fridacoreJNI._GVfsClass__g_reserved4_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_void__void(cPtr, false);
  }

  public void set_g_reserved5(SWIGTYPE_p_f_void__void value) {
    fridacoreJNI._GVfsClass__g_reserved5_set(swigCPtr, this, SWIGTYPE_p_f_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_void__void get_g_reserved5() {
    long cPtr = fridacoreJNI._GVfsClass__g_reserved5_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_void__void(cPtr, false);
  }

  public void set_g_reserved6(SWIGTYPE_p_f_void__void value) {
    fridacoreJNI._GVfsClass__g_reserved6_set(swigCPtr, this, SWIGTYPE_p_f_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_void__void get_g_reserved6() {
    long cPtr = fridacoreJNI._GVfsClass__g_reserved6_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_void__void(cPtr, false);
  }

  public _GVfsClass() {
    this(fridacoreJNI.new__GVfsClass(), true);
  }

}
