/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public class _GVolumeIface {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _GVolumeIface(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_GVolumeIface obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fridacoreJNI.delete__GVolumeIface(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setG_iface(_GTypeInterface value) {
    fridacoreJNI._GVolumeIface_g_iface_set(swigCPtr, this, _GTypeInterface.getCPtr(value), value);
  }

  public _GTypeInterface getG_iface() {
    long cPtr = fridacoreJNI._GVolumeIface_g_iface_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GTypeInterface(cPtr, false);
  }

  public void setChanged(SWIGTYPE_p_f_p__GVolume__void value) {
    fridacoreJNI._GVolumeIface_changed_set(swigCPtr, this, SWIGTYPE_p_f_p__GVolume__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GVolume__void getChanged() {
    long cPtr = fridacoreJNI._GVolumeIface_changed_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GVolume__void(cPtr, false);
  }

  public void setRemoved(SWIGTYPE_p_f_p__GVolume__void value) {
    fridacoreJNI._GVolumeIface_removed_set(swigCPtr, this, SWIGTYPE_p_f_p__GVolume__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GVolume__void getRemoved() {
    long cPtr = fridacoreJNI._GVolumeIface_removed_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GVolume__void(cPtr, false);
  }

  public void setGet_name(SWIGTYPE_p_f_p__GVolume__p_char value) {
    fridacoreJNI._GVolumeIface_get_name_set(swigCPtr, this, SWIGTYPE_p_f_p__GVolume__p_char.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GVolume__p_char getGet_name() {
    long cPtr = fridacoreJNI._GVolumeIface_get_name_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GVolume__p_char(cPtr, false);
  }

  public void setGet_icon(SWIGTYPE_p_f_p__GVolume__p__GIcon value) {
    fridacoreJNI._GVolumeIface_get_icon_set(swigCPtr, this, SWIGTYPE_p_f_p__GVolume__p__GIcon.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GVolume__p__GIcon getGet_icon() {
    long cPtr = fridacoreJNI._GVolumeIface_get_icon_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GVolume__p__GIcon(cPtr, false);
  }

  public void setGet_uuid(SWIGTYPE_p_f_p__GVolume__p_char value) {
    fridacoreJNI._GVolumeIface_get_uuid_set(swigCPtr, this, SWIGTYPE_p_f_p__GVolume__p_char.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GVolume__p_char getGet_uuid() {
    long cPtr = fridacoreJNI._GVolumeIface_get_uuid_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GVolume__p_char(cPtr, false);
  }

  public void setGet_drive(SWIGTYPE_p_f_p__GVolume__p__GDrive value) {
    fridacoreJNI._GVolumeIface_get_drive_set(swigCPtr, this, SWIGTYPE_p_f_p__GVolume__p__GDrive.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GVolume__p__GDrive getGet_drive() {
    long cPtr = fridacoreJNI._GVolumeIface_get_drive_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GVolume__p__GDrive(cPtr, false);
  }

  public void setGet_mount(SWIGTYPE_p_f_p__GVolume__p__GMount value) {
    fridacoreJNI._GVolumeIface_get_mount_set(swigCPtr, this, SWIGTYPE_p_f_p__GVolume__p__GMount.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GVolume__p__GMount getGet_mount() {
    long cPtr = fridacoreJNI._GVolumeIface_get_mount_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GVolume__p__GMount(cPtr, false);
  }

  public void setCan_mount(SWIGTYPE_p_f_p__GVolume__int value) {
    fridacoreJNI._GVolumeIface_can_mount_set(swigCPtr, this, SWIGTYPE_p_f_p__GVolume__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GVolume__int getCan_mount() {
    long cPtr = fridacoreJNI._GVolumeIface_can_mount_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GVolume__int(cPtr, false);
  }

  public void setCan_eject(SWIGTYPE_p_f_p__GVolume__int value) {
    fridacoreJNI._GVolumeIface_can_eject_set(swigCPtr, this, SWIGTYPE_p_f_p__GVolume__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GVolume__int getCan_eject() {
    long cPtr = fridacoreJNI._GVolumeIface_can_eject_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GVolume__int(cPtr, false);
  }

  public void setMount_fn(SWIGTYPE_p_f_p__GVolume_enum_GMountMountFlags_p__GMountOperation_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void value) {
    fridacoreJNI._GVolumeIface_mount_fn_set(swigCPtr, this, SWIGTYPE_p_f_p__GVolume_enum_GMountMountFlags_p__GMountOperation_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GVolume_enum_GMountMountFlags_p__GMountOperation_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void getMount_fn() {
    long cPtr = fridacoreJNI._GVolumeIface_mount_fn_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GVolume_enum_GMountMountFlags_p__GMountOperation_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void(cPtr, false);
  }

  public void setMount_finish(SWIGTYPE_p_f_p__GVolume_p__GAsyncResult_p_p__GError__int value) {
    fridacoreJNI._GVolumeIface_mount_finish_set(swigCPtr, this, SWIGTYPE_p_f_p__GVolume_p__GAsyncResult_p_p__GError__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GVolume_p__GAsyncResult_p_p__GError__int getMount_finish() {
    long cPtr = fridacoreJNI._GVolumeIface_mount_finish_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GVolume_p__GAsyncResult_p_p__GError__int(cPtr, false);
  }

  public void setEject(SWIGTYPE_p_f_p__GVolume_enum_GMountUnmountFlags_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void value) {
    fridacoreJNI._GVolumeIface_eject_set(swigCPtr, this, SWIGTYPE_p_f_p__GVolume_enum_GMountUnmountFlags_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GVolume_enum_GMountUnmountFlags_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void getEject() {
    long cPtr = fridacoreJNI._GVolumeIface_eject_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GVolume_enum_GMountUnmountFlags_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void(cPtr, false);
  }

  public void setEject_finish(SWIGTYPE_p_f_p__GVolume_p__GAsyncResult_p_p__GError__int value) {
    fridacoreJNI._GVolumeIface_eject_finish_set(swigCPtr, this, SWIGTYPE_p_f_p__GVolume_p__GAsyncResult_p_p__GError__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GVolume_p__GAsyncResult_p_p__GError__int getEject_finish() {
    long cPtr = fridacoreJNI._GVolumeIface_eject_finish_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GVolume_p__GAsyncResult_p_p__GError__int(cPtr, false);
  }

  public void setGet_identifier(SWIGTYPE_p_f_p__GVolume_p_q_const__char__p_char value) {
    fridacoreJNI._GVolumeIface_get_identifier_set(swigCPtr, this, SWIGTYPE_p_f_p__GVolume_p_q_const__char__p_char.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GVolume_p_q_const__char__p_char getGet_identifier() {
    long cPtr = fridacoreJNI._GVolumeIface_get_identifier_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GVolume_p_q_const__char__p_char(cPtr, false);
  }

  public void setEnumerate_identifiers(SWIGTYPE_p_f_p__GVolume__p_p_char value) {
    fridacoreJNI._GVolumeIface_enumerate_identifiers_set(swigCPtr, this, SWIGTYPE_p_f_p__GVolume__p_p_char.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GVolume__p_p_char getEnumerate_identifiers() {
    long cPtr = fridacoreJNI._GVolumeIface_enumerate_identifiers_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GVolume__p_p_char(cPtr, false);
  }

  public void setShould_automount(SWIGTYPE_p_f_p__GVolume__int value) {
    fridacoreJNI._GVolumeIface_should_automount_set(swigCPtr, this, SWIGTYPE_p_f_p__GVolume__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GVolume__int getShould_automount() {
    long cPtr = fridacoreJNI._GVolumeIface_should_automount_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GVolume__int(cPtr, false);
  }

  public void setGet_activation_root(SWIGTYPE_p_f_p__GVolume__p__GFile value) {
    fridacoreJNI._GVolumeIface_get_activation_root_set(swigCPtr, this, SWIGTYPE_p_f_p__GVolume__p__GFile.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GVolume__p__GFile getGet_activation_root() {
    long cPtr = fridacoreJNI._GVolumeIface_get_activation_root_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GVolume__p__GFile(cPtr, false);
  }

  public void setEject_with_operation(SWIGTYPE_p_f_p__GVolume_enum_GMountUnmountFlags_p__GMountOperation_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void value) {
    fridacoreJNI._GVolumeIface_eject_with_operation_set(swigCPtr, this, SWIGTYPE_p_f_p__GVolume_enum_GMountUnmountFlags_p__GMountOperation_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GVolume_enum_GMountUnmountFlags_p__GMountOperation_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void getEject_with_operation() {
    long cPtr = fridacoreJNI._GVolumeIface_eject_with_operation_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GVolume_enum_GMountUnmountFlags_p__GMountOperation_p__GCancellable_p_f_p__GObject_p__GAsyncResult_p_void__void_p_void__void(cPtr, false);
  }

  public void setEject_with_operation_finish(SWIGTYPE_p_f_p__GVolume_p__GAsyncResult_p_p__GError__int value) {
    fridacoreJNI._GVolumeIface_eject_with_operation_finish_set(swigCPtr, this, SWIGTYPE_p_f_p__GVolume_p__GAsyncResult_p_p__GError__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GVolume_p__GAsyncResult_p_p__GError__int getEject_with_operation_finish() {
    long cPtr = fridacoreJNI._GVolumeIface_eject_with_operation_finish_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GVolume_p__GAsyncResult_p_p__GError__int(cPtr, false);
  }

  public void setGet_sort_key(SWIGTYPE_p_f_p__GVolume__p_char value) {
    fridacoreJNI._GVolumeIface_get_sort_key_set(swigCPtr, this, SWIGTYPE_p_f_p__GVolume__p_char.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GVolume__p_char getGet_sort_key() {
    long cPtr = fridacoreJNI._GVolumeIface_get_sort_key_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GVolume__p_char(cPtr, false);
  }

  public void setGet_symbolic_icon(SWIGTYPE_p_f_p__GVolume__p__GIcon value) {
    fridacoreJNI._GVolumeIface_get_symbolic_icon_set(swigCPtr, this, SWIGTYPE_p_f_p__GVolume__p__GIcon.getCPtr(value));
  }

  public SWIGTYPE_p_f_p__GVolume__p__GIcon getGet_symbolic_icon() {
    long cPtr = fridacoreJNI._GVolumeIface_get_symbolic_icon_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p__GVolume__p__GIcon(cPtr, false);
  }

  public _GVolumeIface() {
    this(fridacoreJNI.new__GVolumeIface(), true);
  }

}
