/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public final class FridaDeviceType {
  public final static FridaDeviceType FRIDA_DEVICE_TYPE_LOCAL = new FridaDeviceType("FRIDA_DEVICE_TYPE_LOCAL");
  public final static FridaDeviceType FRIDA_DEVICE_TYPE_REMOTE = new FridaDeviceType("FRIDA_DEVICE_TYPE_REMOTE");
  public final static FridaDeviceType FRIDA_DEVICE_TYPE_USB = new FridaDeviceType("FRIDA_DEVICE_TYPE_USB");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FridaDeviceType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + FridaDeviceType.class + " with value " + swigValue);
  }

  private FridaDeviceType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FridaDeviceType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FridaDeviceType(String swigName, FridaDeviceType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FridaDeviceType[] swigValues = { FRIDA_DEVICE_TYPE_LOCAL, FRIDA_DEVICE_TYPE_REMOTE, FRIDA_DEVICE_TYPE_USB };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

