/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public final class FridaUnloadPolicy {
  public final static FridaUnloadPolicy FRIDA_UNLOAD_POLICY_IMMEDIATE = new FridaUnloadPolicy("FRIDA_UNLOAD_POLICY_IMMEDIATE");
  public final static FridaUnloadPolicy FRIDA_UNLOAD_POLICY_RESIDENT = new FridaUnloadPolicy("FRIDA_UNLOAD_POLICY_RESIDENT");
  public final static FridaUnloadPolicy FRIDA_UNLOAD_POLICY_DEFERRED = new FridaUnloadPolicy("FRIDA_UNLOAD_POLICY_DEFERRED");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FridaUnloadPolicy swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + FridaUnloadPolicy.class + " with value " + swigValue);
  }

  private FridaUnloadPolicy(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FridaUnloadPolicy(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FridaUnloadPolicy(String swigName, FridaUnloadPolicy swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FridaUnloadPolicy[] swigValues = { FRIDA_UNLOAD_POLICY_IMMEDIATE, FRIDA_UNLOAD_POLICY_RESIDENT, FRIDA_UNLOAD_POLICY_DEFERRED };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

