/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public final class GAppInfoCreateFlags {
  public final static GAppInfoCreateFlags G_APP_INFO_CREATE_NONE = new GAppInfoCreateFlags("G_APP_INFO_CREATE_NONE", fridacoreJNI.G_APP_INFO_CREATE_NONE_get());
  public final static GAppInfoCreateFlags G_APP_INFO_CREATE_NEEDS_TERMINAL = new GAppInfoCreateFlags("G_APP_INFO_CREATE_NEEDS_TERMINAL", fridacoreJNI.G_APP_INFO_CREATE_NEEDS_TERMINAL_get());
  public final static GAppInfoCreateFlags G_APP_INFO_CREATE_SUPPORTS_URIS = new GAppInfoCreateFlags("G_APP_INFO_CREATE_SUPPORTS_URIS", fridacoreJNI.G_APP_INFO_CREATE_SUPPORTS_URIS_get());
  public final static GAppInfoCreateFlags G_APP_INFO_CREATE_SUPPORTS_STARTUP_NOTIFICATION = new GAppInfoCreateFlags("G_APP_INFO_CREATE_SUPPORTS_STARTUP_NOTIFICATION", fridacoreJNI.G_APP_INFO_CREATE_SUPPORTS_STARTUP_NOTIFICATION_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GAppInfoCreateFlags swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GAppInfoCreateFlags.class + " with value " + swigValue);
  }

  private GAppInfoCreateFlags(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GAppInfoCreateFlags(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GAppInfoCreateFlags(String swigName, GAppInfoCreateFlags swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GAppInfoCreateFlags[] swigValues = { G_APP_INFO_CREATE_NONE, G_APP_INFO_CREATE_NEEDS_TERMINAL, G_APP_INFO_CREATE_SUPPORTS_URIS, G_APP_INFO_CREATE_SUPPORTS_STARTUP_NOTIFICATION };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

