/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public final class GConverterFlags {
  public final static GConverterFlags G_CONVERTER_NO_FLAGS = new GConverterFlags("G_CONVERTER_NO_FLAGS", fridacoreJNI.G_CONVERTER_NO_FLAGS_get());
  public final static GConverterFlags G_CONVERTER_INPUT_AT_END = new GConverterFlags("G_CONVERTER_INPUT_AT_END", fridacoreJNI.G_CONVERTER_INPUT_AT_END_get());
  public final static GConverterFlags G_CONVERTER_FLUSH = new GConverterFlags("G_CONVERTER_FLUSH", fridacoreJNI.G_CONVERTER_FLUSH_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GConverterFlags swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GConverterFlags.class + " with value " + swigValue);
  }

  private GConverterFlags(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GConverterFlags(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GConverterFlags(String swigName, GConverterFlags swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GConverterFlags[] swigValues = { G_CONVERTER_NO_FLAGS, G_CONVERTER_INPUT_AT_END, G_CONVERTER_FLUSH };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

