/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public final class GDBusProxyFlags {
  public final static GDBusProxyFlags G_DBUS_PROXY_FLAGS_NONE = new GDBusProxyFlags("G_DBUS_PROXY_FLAGS_NONE", fridacoreJNI.G_DBUS_PROXY_FLAGS_NONE_get());
  public final static GDBusProxyFlags G_DBUS_PROXY_FLAGS_DO_NOT_LOAD_PROPERTIES = new GDBusProxyFlags("G_DBUS_PROXY_FLAGS_DO_NOT_LOAD_PROPERTIES", fridacoreJNI.G_DBUS_PROXY_FLAGS_DO_NOT_LOAD_PROPERTIES_get());
  public final static GDBusProxyFlags G_DBUS_PROXY_FLAGS_DO_NOT_CONNECT_SIGNALS = new GDBusProxyFlags("G_DBUS_PROXY_FLAGS_DO_NOT_CONNECT_SIGNALS", fridacoreJNI.G_DBUS_PROXY_FLAGS_DO_NOT_CONNECT_SIGNALS_get());
  public final static GDBusProxyFlags G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START = new GDBusProxyFlags("G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START", fridacoreJNI.G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START_get());
  public final static GDBusProxyFlags G_DBUS_PROXY_FLAGS_GET_INVALIDATED_PROPERTIES = new GDBusProxyFlags("G_DBUS_PROXY_FLAGS_GET_INVALIDATED_PROPERTIES", fridacoreJNI.G_DBUS_PROXY_FLAGS_GET_INVALIDATED_PROPERTIES_get());
  public final static GDBusProxyFlags G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START_AT_CONSTRUCTION = new GDBusProxyFlags("G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START_AT_CONSTRUCTION", fridacoreJNI.G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START_AT_CONSTRUCTION_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GDBusProxyFlags swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GDBusProxyFlags.class + " with value " + swigValue);
  }

  private GDBusProxyFlags(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GDBusProxyFlags(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GDBusProxyFlags(String swigName, GDBusProxyFlags swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GDBusProxyFlags[] swigValues = { G_DBUS_PROXY_FLAGS_NONE, G_DBUS_PROXY_FLAGS_DO_NOT_LOAD_PROPERTIES, G_DBUS_PROXY_FLAGS_DO_NOT_CONNECT_SIGNALS, G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START, G_DBUS_PROXY_FLAGS_GET_INVALIDATED_PROPERTIES, G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START_AT_CONSTRUCTION };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

