/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public final class GDBusPropertyInfoFlags {
  public final static GDBusPropertyInfoFlags G_DBUS_PROPERTY_INFO_FLAGS_NONE = new GDBusPropertyInfoFlags("G_DBUS_PROPERTY_INFO_FLAGS_NONE", fridacoreJNI.G_DBUS_PROPERTY_INFO_FLAGS_NONE_get());
  public final static GDBusPropertyInfoFlags G_DBUS_PROPERTY_INFO_FLAGS_READABLE = new GDBusPropertyInfoFlags("G_DBUS_PROPERTY_INFO_FLAGS_READABLE", fridacoreJNI.G_DBUS_PROPERTY_INFO_FLAGS_READABLE_get());
  public final static GDBusPropertyInfoFlags G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE = new GDBusPropertyInfoFlags("G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE", fridacoreJNI.G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GDBusPropertyInfoFlags swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GDBusPropertyInfoFlags.class + " with value " + swigValue);
  }

  private GDBusPropertyInfoFlags(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GDBusPropertyInfoFlags(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GDBusPropertyInfoFlags(String swigName, GDBusPropertyInfoFlags swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GDBusPropertyInfoFlags[] swigValues = { G_DBUS_PROPERTY_INFO_FLAGS_NONE, G_DBUS_PROPERTY_INFO_FLAGS_READABLE, G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

