/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public final class GDBusMessageHeaderField {
  public final static GDBusMessageHeaderField G_DBUS_MESSAGE_HEADER_FIELD_INVALID = new GDBusMessageHeaderField("G_DBUS_MESSAGE_HEADER_FIELD_INVALID");
  public final static GDBusMessageHeaderField G_DBUS_MESSAGE_HEADER_FIELD_PATH = new GDBusMessageHeaderField("G_DBUS_MESSAGE_HEADER_FIELD_PATH");
  public final static GDBusMessageHeaderField G_DBUS_MESSAGE_HEADER_FIELD_INTERFACE = new GDBusMessageHeaderField("G_DBUS_MESSAGE_HEADER_FIELD_INTERFACE");
  public final static GDBusMessageHeaderField G_DBUS_MESSAGE_HEADER_FIELD_MEMBER = new GDBusMessageHeaderField("G_DBUS_MESSAGE_HEADER_FIELD_MEMBER");
  public final static GDBusMessageHeaderField G_DBUS_MESSAGE_HEADER_FIELD_ERROR_NAME = new GDBusMessageHeaderField("G_DBUS_MESSAGE_HEADER_FIELD_ERROR_NAME");
  public final static GDBusMessageHeaderField G_DBUS_MESSAGE_HEADER_FIELD_REPLY_SERIAL = new GDBusMessageHeaderField("G_DBUS_MESSAGE_HEADER_FIELD_REPLY_SERIAL");
  public final static GDBusMessageHeaderField G_DBUS_MESSAGE_HEADER_FIELD_DESTINATION = new GDBusMessageHeaderField("G_DBUS_MESSAGE_HEADER_FIELD_DESTINATION");
  public final static GDBusMessageHeaderField G_DBUS_MESSAGE_HEADER_FIELD_SENDER = new GDBusMessageHeaderField("G_DBUS_MESSAGE_HEADER_FIELD_SENDER");
  public final static GDBusMessageHeaderField G_DBUS_MESSAGE_HEADER_FIELD_SIGNATURE = new GDBusMessageHeaderField("G_DBUS_MESSAGE_HEADER_FIELD_SIGNATURE");
  public final static GDBusMessageHeaderField G_DBUS_MESSAGE_HEADER_FIELD_NUM_UNIX_FDS = new GDBusMessageHeaderField("G_DBUS_MESSAGE_HEADER_FIELD_NUM_UNIX_FDS");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GDBusMessageHeaderField swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GDBusMessageHeaderField.class + " with value " + swigValue);
  }

  private GDBusMessageHeaderField(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GDBusMessageHeaderField(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GDBusMessageHeaderField(String swigName, GDBusMessageHeaderField swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GDBusMessageHeaderField[] swigValues = { G_DBUS_MESSAGE_HEADER_FIELD_INVALID, G_DBUS_MESSAGE_HEADER_FIELD_PATH, G_DBUS_MESSAGE_HEADER_FIELD_INTERFACE, G_DBUS_MESSAGE_HEADER_FIELD_MEMBER, G_DBUS_MESSAGE_HEADER_FIELD_ERROR_NAME, G_DBUS_MESSAGE_HEADER_FIELD_REPLY_SERIAL, G_DBUS_MESSAGE_HEADER_FIELD_DESTINATION, G_DBUS_MESSAGE_HEADER_FIELD_SENDER, G_DBUS_MESSAGE_HEADER_FIELD_SIGNATURE, G_DBUS_MESSAGE_HEADER_FIELD_NUM_UNIX_FDS };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

