/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public final class GDBusMessageFlags {
  public final static GDBusMessageFlags G_DBUS_MESSAGE_FLAGS_NONE = new GDBusMessageFlags("G_DBUS_MESSAGE_FLAGS_NONE", fridacoreJNI.G_DBUS_MESSAGE_FLAGS_NONE_get());
  public final static GDBusMessageFlags G_DBUS_MESSAGE_FLAGS_NO_REPLY_EXPECTED = new GDBusMessageFlags("G_DBUS_MESSAGE_FLAGS_NO_REPLY_EXPECTED", fridacoreJNI.G_DBUS_MESSAGE_FLAGS_NO_REPLY_EXPECTED_get());
  public final static GDBusMessageFlags G_DBUS_MESSAGE_FLAGS_NO_AUTO_START = new GDBusMessageFlags("G_DBUS_MESSAGE_FLAGS_NO_AUTO_START", fridacoreJNI.G_DBUS_MESSAGE_FLAGS_NO_AUTO_START_get());
  public final static GDBusMessageFlags G_DBUS_MESSAGE_FLAGS_ALLOW_INTERACTIVE_AUTHORIZATION = new GDBusMessageFlags("G_DBUS_MESSAGE_FLAGS_ALLOW_INTERACTIVE_AUTHORIZATION", fridacoreJNI.G_DBUS_MESSAGE_FLAGS_ALLOW_INTERACTIVE_AUTHORIZATION_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GDBusMessageFlags swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GDBusMessageFlags.class + " with value " + swigValue);
  }

  private GDBusMessageFlags(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GDBusMessageFlags(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GDBusMessageFlags(String swigName, GDBusMessageFlags swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GDBusMessageFlags[] swigValues = { G_DBUS_MESSAGE_FLAGS_NONE, G_DBUS_MESSAGE_FLAGS_NO_REPLY_EXPECTED, G_DBUS_MESSAGE_FLAGS_NO_AUTO_START, G_DBUS_MESSAGE_FLAGS_ALLOW_INTERACTIVE_AUTHORIZATION };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

