/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public final class GDBusConnectionFlags {
  public final static GDBusConnectionFlags G_DBUS_CONNECTION_FLAGS_NONE = new GDBusConnectionFlags("G_DBUS_CONNECTION_FLAGS_NONE", fridacoreJNI.G_DBUS_CONNECTION_FLAGS_NONE_get());
  public final static GDBusConnectionFlags G_DBUS_CONNECTION_FLAGS_AUTHENTICATION_CLIENT = new GDBusConnectionFlags("G_DBUS_CONNECTION_FLAGS_AUTHENTICATION_CLIENT", fridacoreJNI.G_DBUS_CONNECTION_FLAGS_AUTHENTICATION_CLIENT_get());
  public final static GDBusConnectionFlags G_DBUS_CONNECTION_FLAGS_AUTHENTICATION_SERVER = new GDBusConnectionFlags("G_DBUS_CONNECTION_FLAGS_AUTHENTICATION_SERVER", fridacoreJNI.G_DBUS_CONNECTION_FLAGS_AUTHENTICATION_SERVER_get());
  public final static GDBusConnectionFlags G_DBUS_CONNECTION_FLAGS_AUTHENTICATION_ALLOW_ANONYMOUS = new GDBusConnectionFlags("G_DBUS_CONNECTION_FLAGS_AUTHENTICATION_ALLOW_ANONYMOUS", fridacoreJNI.G_DBUS_CONNECTION_FLAGS_AUTHENTICATION_ALLOW_ANONYMOUS_get());
  public final static GDBusConnectionFlags G_DBUS_CONNECTION_FLAGS_MESSAGE_BUS_CONNECTION = new GDBusConnectionFlags("G_DBUS_CONNECTION_FLAGS_MESSAGE_BUS_CONNECTION", fridacoreJNI.G_DBUS_CONNECTION_FLAGS_MESSAGE_BUS_CONNECTION_get());
  public final static GDBusConnectionFlags G_DBUS_CONNECTION_FLAGS_DELAY_MESSAGE_PROCESSING = new GDBusConnectionFlags("G_DBUS_CONNECTION_FLAGS_DELAY_MESSAGE_PROCESSING", fridacoreJNI.G_DBUS_CONNECTION_FLAGS_DELAY_MESSAGE_PROCESSING_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GDBusConnectionFlags swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GDBusConnectionFlags.class + " with value " + swigValue);
  }

  private GDBusConnectionFlags(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GDBusConnectionFlags(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GDBusConnectionFlags(String swigName, GDBusConnectionFlags swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GDBusConnectionFlags[] swigValues = { G_DBUS_CONNECTION_FLAGS_NONE, G_DBUS_CONNECTION_FLAGS_AUTHENTICATION_CLIENT, G_DBUS_CONNECTION_FLAGS_AUTHENTICATION_SERVER, G_DBUS_CONNECTION_FLAGS_AUTHENTICATION_ALLOW_ANONYMOUS, G_DBUS_CONNECTION_FLAGS_MESSAGE_BUS_CONNECTION, G_DBUS_CONNECTION_FLAGS_DELAY_MESSAGE_PROCESSING };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

