/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public final class GFileMonitorEvent {
  public final static GFileMonitorEvent G_FILE_MONITOR_EVENT_CHANGED = new GFileMonitorEvent("G_FILE_MONITOR_EVENT_CHANGED");
  public final static GFileMonitorEvent G_FILE_MONITOR_EVENT_CHANGES_DONE_HINT = new GFileMonitorEvent("G_FILE_MONITOR_EVENT_CHANGES_DONE_HINT");
  public final static GFileMonitorEvent G_FILE_MONITOR_EVENT_DELETED = new GFileMonitorEvent("G_FILE_MONITOR_EVENT_DELETED");
  public final static GFileMonitorEvent G_FILE_MONITOR_EVENT_CREATED = new GFileMonitorEvent("G_FILE_MONITOR_EVENT_CREATED");
  public final static GFileMonitorEvent G_FILE_MONITOR_EVENT_ATTRIBUTE_CHANGED = new GFileMonitorEvent("G_FILE_MONITOR_EVENT_ATTRIBUTE_CHANGED");
  public final static GFileMonitorEvent G_FILE_MONITOR_EVENT_PRE_UNMOUNT = new GFileMonitorEvent("G_FILE_MONITOR_EVENT_PRE_UNMOUNT");
  public final static GFileMonitorEvent G_FILE_MONITOR_EVENT_UNMOUNTED = new GFileMonitorEvent("G_FILE_MONITOR_EVENT_UNMOUNTED");
  public final static GFileMonitorEvent G_FILE_MONITOR_EVENT_MOVED = new GFileMonitorEvent("G_FILE_MONITOR_EVENT_MOVED");
  public final static GFileMonitorEvent G_FILE_MONITOR_EVENT_RENAMED = new GFileMonitorEvent("G_FILE_MONITOR_EVENT_RENAMED");
  public final static GFileMonitorEvent G_FILE_MONITOR_EVENT_MOVED_IN = new GFileMonitorEvent("G_FILE_MONITOR_EVENT_MOVED_IN");
  public final static GFileMonitorEvent G_FILE_MONITOR_EVENT_MOVED_OUT = new GFileMonitorEvent("G_FILE_MONITOR_EVENT_MOVED_OUT");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GFileMonitorEvent swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GFileMonitorEvent.class + " with value " + swigValue);
  }

  private GFileMonitorEvent(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GFileMonitorEvent(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GFileMonitorEvent(String swigName, GFileMonitorEvent swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GFileMonitorEvent[] swigValues = { G_FILE_MONITOR_EVENT_CHANGED, G_FILE_MONITOR_EVENT_CHANGES_DONE_HINT, G_FILE_MONITOR_EVENT_DELETED, G_FILE_MONITOR_EVENT_CREATED, G_FILE_MONITOR_EVENT_ATTRIBUTE_CHANGED, G_FILE_MONITOR_EVENT_PRE_UNMOUNT, G_FILE_MONITOR_EVENT_UNMOUNTED, G_FILE_MONITOR_EVENT_MOVED, G_FILE_MONITOR_EVENT_RENAMED, G_FILE_MONITOR_EVENT_MOVED_IN, G_FILE_MONITOR_EVENT_MOVED_OUT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

