/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public final class GFilesystemPreviewType {
  public final static GFilesystemPreviewType G_FILESYSTEM_PREVIEW_TYPE_IF_ALWAYS = new GFilesystemPreviewType("G_FILESYSTEM_PREVIEW_TYPE_IF_ALWAYS", fridacoreJNI.G_FILESYSTEM_PREVIEW_TYPE_IF_ALWAYS_get());
  public final static GFilesystemPreviewType G_FILESYSTEM_PREVIEW_TYPE_IF_LOCAL = new GFilesystemPreviewType("G_FILESYSTEM_PREVIEW_TYPE_IF_LOCAL");
  public final static GFilesystemPreviewType G_FILESYSTEM_PREVIEW_TYPE_NEVER = new GFilesystemPreviewType("G_FILESYSTEM_PREVIEW_TYPE_NEVER");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GFilesystemPreviewType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GFilesystemPreviewType.class + " with value " + swigValue);
  }

  private GFilesystemPreviewType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GFilesystemPreviewType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GFilesystemPreviewType(String swigName, GFilesystemPreviewType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GFilesystemPreviewType[] swigValues = { G_FILESYSTEM_PREVIEW_TYPE_IF_ALWAYS, G_FILESYSTEM_PREVIEW_TYPE_IF_LOCAL, G_FILESYSTEM_PREVIEW_TYPE_NEVER };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

