/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public final class GNetworkConnectivity {
  public final static GNetworkConnectivity G_NETWORK_CONNECTIVITY_LOCAL = new GNetworkConnectivity("G_NETWORK_CONNECTIVITY_LOCAL", fridacoreJNI.G_NETWORK_CONNECTIVITY_LOCAL_get());
  public final static GNetworkConnectivity G_NETWORK_CONNECTIVITY_LIMITED = new GNetworkConnectivity("G_NETWORK_CONNECTIVITY_LIMITED", fridacoreJNI.G_NETWORK_CONNECTIVITY_LIMITED_get());
  public final static GNetworkConnectivity G_NETWORK_CONNECTIVITY_PORTAL = new GNetworkConnectivity("G_NETWORK_CONNECTIVITY_PORTAL", fridacoreJNI.G_NETWORK_CONNECTIVITY_PORTAL_get());
  public final static GNetworkConnectivity G_NETWORK_CONNECTIVITY_FULL = new GNetworkConnectivity("G_NETWORK_CONNECTIVITY_FULL", fridacoreJNI.G_NETWORK_CONNECTIVITY_FULL_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GNetworkConnectivity swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GNetworkConnectivity.class + " with value " + swigValue);
  }

  private GNetworkConnectivity(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GNetworkConnectivity(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GNetworkConnectivity(String swigName, GNetworkConnectivity swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GNetworkConnectivity[] swigValues = { G_NETWORK_CONNECTIVITY_LOCAL, G_NETWORK_CONNECTIVITY_LIMITED, G_NETWORK_CONNECTIVITY_PORTAL, G_NETWORK_CONNECTIVITY_FULL };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

