/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public final class GNumberParserError {
  public final static GNumberParserError G_NUMBER_PARSER_ERROR_INVALID = new GNumberParserError("G_NUMBER_PARSER_ERROR_INVALID");
  public final static GNumberParserError G_NUMBER_PARSER_ERROR_OUT_OF_BOUNDS = new GNumberParserError("G_NUMBER_PARSER_ERROR_OUT_OF_BOUNDS");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GNumberParserError swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GNumberParserError.class + " with value " + swigValue);
  }

  private GNumberParserError(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GNumberParserError(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GNumberParserError(String swigName, GNumberParserError swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GNumberParserError[] swigValues = { G_NUMBER_PARSER_ERROR_INVALID, G_NUMBER_PARSER_ERROR_OUT_OF_BOUNDS };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

