/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public final class GParamFlags {
  public final static GParamFlags G_PARAM_READABLE = new GParamFlags("G_PARAM_READABLE", fridacoreJNI.G_PARAM_READABLE_get());
  public final static GParamFlags G_PARAM_WRITABLE = new GParamFlags("G_PARAM_WRITABLE", fridacoreJNI.G_PARAM_WRITABLE_get());
  public final static GParamFlags G_PARAM_READWRITE = new GParamFlags("G_PARAM_READWRITE", fridacoreJNI.G_PARAM_READWRITE_get());
  public final static GParamFlags G_PARAM_CONSTRUCT = new GParamFlags("G_PARAM_CONSTRUCT", fridacoreJNI.G_PARAM_CONSTRUCT_get());
  public final static GParamFlags G_PARAM_CONSTRUCT_ONLY = new GParamFlags("G_PARAM_CONSTRUCT_ONLY", fridacoreJNI.G_PARAM_CONSTRUCT_ONLY_get());
  public final static GParamFlags G_PARAM_LAX_VALIDATION = new GParamFlags("G_PARAM_LAX_VALIDATION", fridacoreJNI.G_PARAM_LAX_VALIDATION_get());
  public final static GParamFlags G_PARAM_STATIC_NAME = new GParamFlags("G_PARAM_STATIC_NAME", fridacoreJNI.G_PARAM_STATIC_NAME_get());
  public final static GParamFlags G_PARAM_PRIVATE = new GParamFlags("G_PARAM_PRIVATE", fridacoreJNI.G_PARAM_PRIVATE_get());
  public final static GParamFlags G_PARAM_STATIC_NICK = new GParamFlags("G_PARAM_STATIC_NICK", fridacoreJNI.G_PARAM_STATIC_NICK_get());
  public final static GParamFlags G_PARAM_STATIC_BLURB = new GParamFlags("G_PARAM_STATIC_BLURB", fridacoreJNI.G_PARAM_STATIC_BLURB_get());
  public final static GParamFlags G_PARAM_EXPLICIT_NOTIFY = new GParamFlags("G_PARAM_EXPLICIT_NOTIFY", fridacoreJNI.G_PARAM_EXPLICIT_NOTIFY_get());
  public final static GParamFlags G_PARAM_DEPRECATED = new GParamFlags("G_PARAM_DEPRECATED", fridacoreJNI.G_PARAM_DEPRECATED_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GParamFlags swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GParamFlags.class + " with value " + swigValue);
  }

  private GParamFlags(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GParamFlags(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GParamFlags(String swigName, GParamFlags swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GParamFlags[] swigValues = { G_PARAM_READABLE, G_PARAM_WRITABLE, G_PARAM_READWRITE, G_PARAM_CONSTRUCT, G_PARAM_CONSTRUCT_ONLY, G_PARAM_LAX_VALIDATION, G_PARAM_STATIC_NAME, G_PARAM_PRIVATE, G_PARAM_STATIC_NICK, G_PARAM_STATIC_BLURB, G_PARAM_EXPLICIT_NOTIFY, G_PARAM_DEPRECATED };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

