/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public final class GResolverRecordType {
  public final static GResolverRecordType G_RESOLVER_RECORD_SRV = new GResolverRecordType("G_RESOLVER_RECORD_SRV", fridacoreJNI.G_RESOLVER_RECORD_SRV_get());
  public final static GResolverRecordType G_RESOLVER_RECORD_MX = new GResolverRecordType("G_RESOLVER_RECORD_MX");
  public final static GResolverRecordType G_RESOLVER_RECORD_TXT = new GResolverRecordType("G_RESOLVER_RECORD_TXT");
  public final static GResolverRecordType G_RESOLVER_RECORD_SOA = new GResolverRecordType("G_RESOLVER_RECORD_SOA");
  public final static GResolverRecordType G_RESOLVER_RECORD_NS = new GResolverRecordType("G_RESOLVER_RECORD_NS");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GResolverRecordType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GResolverRecordType.class + " with value " + swigValue);
  }

  private GResolverRecordType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GResolverRecordType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GResolverRecordType(String swigName, GResolverRecordType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GResolverRecordType[] swigValues = { G_RESOLVER_RECORD_SRV, G_RESOLVER_RECORD_MX, G_RESOLVER_RECORD_TXT, G_RESOLVER_RECORD_SOA, G_RESOLVER_RECORD_NS };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

