/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public final class GSettingsBindFlags {
  public final static GSettingsBindFlags G_SETTINGS_BIND_DEFAULT = new GSettingsBindFlags("G_SETTINGS_BIND_DEFAULT");
  public final static GSettingsBindFlags G_SETTINGS_BIND_GET = new GSettingsBindFlags("G_SETTINGS_BIND_GET", fridacoreJNI.G_SETTINGS_BIND_GET_get());
  public final static GSettingsBindFlags G_SETTINGS_BIND_SET = new GSettingsBindFlags("G_SETTINGS_BIND_SET", fridacoreJNI.G_SETTINGS_BIND_SET_get());
  public final static GSettingsBindFlags G_SETTINGS_BIND_NO_SENSITIVITY = new GSettingsBindFlags("G_SETTINGS_BIND_NO_SENSITIVITY", fridacoreJNI.G_SETTINGS_BIND_NO_SENSITIVITY_get());
  public final static GSettingsBindFlags G_SETTINGS_BIND_GET_NO_CHANGES = new GSettingsBindFlags("G_SETTINGS_BIND_GET_NO_CHANGES", fridacoreJNI.G_SETTINGS_BIND_GET_NO_CHANGES_get());
  public final static GSettingsBindFlags G_SETTINGS_BIND_INVERT_BOOLEAN = new GSettingsBindFlags("G_SETTINGS_BIND_INVERT_BOOLEAN", fridacoreJNI.G_SETTINGS_BIND_INVERT_BOOLEAN_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GSettingsBindFlags swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GSettingsBindFlags.class + " with value " + swigValue);
  }

  private GSettingsBindFlags(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GSettingsBindFlags(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GSettingsBindFlags(String swigName, GSettingsBindFlags swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GSettingsBindFlags[] swigValues = { G_SETTINGS_BIND_DEFAULT, G_SETTINGS_BIND_GET, G_SETTINGS_BIND_SET, G_SETTINGS_BIND_NO_SENSITIVITY, G_SETTINGS_BIND_GET_NO_CHANGES, G_SETTINGS_BIND_INVERT_BOOLEAN };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

