/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public final class GSocketType {
  public final static GSocketType G_SOCKET_TYPE_INVALID = new GSocketType("G_SOCKET_TYPE_INVALID");
  public final static GSocketType G_SOCKET_TYPE_STREAM = new GSocketType("G_SOCKET_TYPE_STREAM");
  public final static GSocketType G_SOCKET_TYPE_DATAGRAM = new GSocketType("G_SOCKET_TYPE_DATAGRAM");
  public final static GSocketType G_SOCKET_TYPE_SEQPACKET = new GSocketType("G_SOCKET_TYPE_SEQPACKET");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GSocketType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GSocketType.class + " with value " + swigValue);
  }

  private GSocketType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GSocketType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GSocketType(String swigName, GSocketType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GSocketType[] swigValues = { G_SOCKET_TYPE_INVALID, G_SOCKET_TYPE_STREAM, G_SOCKET_TYPE_DATAGRAM, G_SOCKET_TYPE_SEQPACKET };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

