/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public final class GSocketFamily {
  public final static GSocketFamily G_SOCKET_FAMILY_INVALID = new GSocketFamily("G_SOCKET_FAMILY_INVALID");
  public final static GSocketFamily G_SOCKET_FAMILY_UNIX = new GSocketFamily("G_SOCKET_FAMILY_UNIX", fridacoreJNI.G_SOCKET_FAMILY_UNIX_get());
  public final static GSocketFamily G_SOCKET_FAMILY_IPV4 = new GSocketFamily("G_SOCKET_FAMILY_IPV4", fridacoreJNI.G_SOCKET_FAMILY_IPV4_get());
  public final static GSocketFamily G_SOCKET_FAMILY_IPV6 = new GSocketFamily("G_SOCKET_FAMILY_IPV6", fridacoreJNI.G_SOCKET_FAMILY_IPV6_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GSocketFamily swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GSocketFamily.class + " with value " + swigValue);
  }

  private GSocketFamily(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GSocketFamily(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GSocketFamily(String swigName, GSocketFamily swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GSocketFamily[] swigValues = { G_SOCKET_FAMILY_INVALID, G_SOCKET_FAMILY_UNIX, G_SOCKET_FAMILY_IPV4, G_SOCKET_FAMILY_IPV6 };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

