/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public class GStaticMutex {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GStaticMutex(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GStaticMutex obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fridacoreJNI.delete_GStaticMutex(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMutex(_GMutex value) {
    fridacoreJNI.GStaticMutex_mutex_set(swigCPtr, this, _GMutex.getCPtr(value), value);
  }

  public _GMutex getMutex() {
    long cPtr = fridacoreJNI.GStaticMutex_mutex_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _GMutex(cPtr, false);
  }

  public void setUnused(SWIGTYPE_p_pthread_mutex_t value) {
    fridacoreJNI.GStaticMutex_unused_set(swigCPtr, this, SWIGTYPE_p_pthread_mutex_t.getCPtr(value));
  }

  public SWIGTYPE_p_pthread_mutex_t getUnused() {
    return new SWIGTYPE_p_pthread_mutex_t(fridacoreJNI.GStaticMutex_unused_get(swigCPtr, this), true);
  }

  public GStaticMutex() {
    this(fridacoreJNI.new_GStaticMutex(), true);
  }

}
