/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public class GTestLogMsg {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GTestLogMsg(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GTestLogMsg obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        fridacoreJNI.delete_GTestLogMsg(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLog_type(GTestLogType value) {
    fridacoreJNI.GTestLogMsg_log_type_set(swigCPtr, this, value.swigValue());
  }

  public GTestLogType getLog_type() {
    return GTestLogType.swigToEnum(fridacoreJNI.GTestLogMsg_log_type_get(swigCPtr, this));
  }

  public void setN_strings(long value) {
    fridacoreJNI.GTestLogMsg_n_strings_set(swigCPtr, this, value);
  }

  public long getN_strings() {
    return fridacoreJNI.GTestLogMsg_n_strings_get(swigCPtr, this);
  }

  public void setStrings(SWIGTYPE_p_p_char value) {
    fridacoreJNI.GTestLogMsg_strings_set(swigCPtr, this, SWIGTYPE_p_p_char.getCPtr(value));
  }

  public SWIGTYPE_p_p_char getStrings() {
    long cPtr = fridacoreJNI.GTestLogMsg_strings_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_char(cPtr, false);
  }

  public void setN_nums(long value) {
    fridacoreJNI.GTestLogMsg_n_nums_set(swigCPtr, this, value);
  }

  public long getN_nums() {
    return fridacoreJNI.GTestLogMsg_n_nums_get(swigCPtr, this);
  }

  public void setNums(SWIGTYPE_p_long_double value) {
    fridacoreJNI.GTestLogMsg_nums_set(swigCPtr, this, SWIGTYPE_p_long_double.getCPtr(value));
  }

  public SWIGTYPE_p_long_double getNums() {
    long cPtr = fridacoreJNI.GTestLogMsg_nums_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_long_double(cPtr, false);
  }

  public GTestLogMsg() {
    this(fridacoreJNI.new_GTestLogMsg(), true);
  }

}
