/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public final class GTlsInteractionResult {
  public final static GTlsInteractionResult G_TLS_INTERACTION_UNHANDLED = new GTlsInteractionResult("G_TLS_INTERACTION_UNHANDLED");
  public final static GTlsInteractionResult G_TLS_INTERACTION_HANDLED = new GTlsInteractionResult("G_TLS_INTERACTION_HANDLED");
  public final static GTlsInteractionResult G_TLS_INTERACTION_FAILED = new GTlsInteractionResult("G_TLS_INTERACTION_FAILED");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GTlsInteractionResult swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GTlsInteractionResult.class + " with value " + swigValue);
  }

  private GTlsInteractionResult(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GTlsInteractionResult(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GTlsInteractionResult(String swigName, GTlsInteractionResult swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GTlsInteractionResult[] swigValues = { G_TLS_INTERACTION_UNHANDLED, G_TLS_INTERACTION_HANDLED, G_TLS_INTERACTION_FAILED };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

