/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public final class GUnixSocketAddressType {
  public final static GUnixSocketAddressType G_UNIX_SOCKET_ADDRESS_INVALID = new GUnixSocketAddressType("G_UNIX_SOCKET_ADDRESS_INVALID");
  public final static GUnixSocketAddressType G_UNIX_SOCKET_ADDRESS_ANONYMOUS = new GUnixSocketAddressType("G_UNIX_SOCKET_ADDRESS_ANONYMOUS");
  public final static GUnixSocketAddressType G_UNIX_SOCKET_ADDRESS_PATH = new GUnixSocketAddressType("G_UNIX_SOCKET_ADDRESS_PATH");
  public final static GUnixSocketAddressType G_UNIX_SOCKET_ADDRESS_ABSTRACT = new GUnixSocketAddressType("G_UNIX_SOCKET_ADDRESS_ABSTRACT");
  public final static GUnixSocketAddressType G_UNIX_SOCKET_ADDRESS_ABSTRACT_PADDED = new GUnixSocketAddressType("G_UNIX_SOCKET_ADDRESS_ABSTRACT_PADDED");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GUnixSocketAddressType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GUnixSocketAddressType.class + " with value " + swigValue);
  }

  private GUnixSocketAddressType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GUnixSocketAddressType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GUnixSocketAddressType(String swigName, GUnixSocketAddressType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GUnixSocketAddressType[] swigValues = { G_UNIX_SOCKET_ADDRESS_INVALID, G_UNIX_SOCKET_ADDRESS_ANONYMOUS, G_UNIX_SOCKET_ADDRESS_PATH, G_UNIX_SOCKET_ADDRESS_ABSTRACT, G_UNIX_SOCKET_ADDRESS_ABSTRACT_PADDED };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

