/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public final class JsonPathError {
  public final static JsonPathError JSON_PATH_ERROR_INVALID_QUERY = new JsonPathError("JSON_PATH_ERROR_INVALID_QUERY");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static JsonPathError swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + JsonPathError.class + " with value " + swigValue);
  }

  private JsonPathError(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private JsonPathError(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private JsonPathError(String swigName, JsonPathError swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static JsonPathError[] swigValues = { JSON_PATH_ERROR_INVALID_QUERY };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

