/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public class SWIGTYPE_p_f_p__GTlsDatabase_p__GTlsCertificate_p_q_const__char_p__GSocketConnectable_p__GTlsInteraction_enum_GTlsDatabaseVerifyFlags_p__GCancellable_p_p__GError__GTlsCertificateFlags {
  private transient long swigCPtr;

  protected SWIGTYPE_p_f_p__GTlsDatabase_p__GTlsCertificate_p_q_const__char_p__GSocketConnectable_p__GTlsInteraction_enum_GTlsDatabaseVerifyFlags_p__GCancellable_p_p__GError__GTlsCertificateFlags(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_f_p__GTlsDatabase_p__GTlsCertificate_p_q_const__char_p__GSocketConnectable_p__GTlsInteraction_enum_GTlsDatabaseVerifyFlags_p__GCancellable_p_p__GError__GTlsCertificateFlags() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_f_p__GTlsDatabase_p__GTlsCertificate_p_q_const__char_p__GSocketConnectable_p__GTlsInteraction_enum_GTlsDatabaseVerifyFlags_p__GCancellable_p_p__GError__GTlsCertificateFlags obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

