/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public class SWIGTYPE_p_f_p_f_p_void__p_void_p_void_unsigned_long_int_int_enum_GThreadPriority_p_void_p_p__GError__void {
  private transient long swigCPtr;

  protected SWIGTYPE_p_f_p_f_p_void__p_void_p_void_unsigned_long_int_int_enum_GThreadPriority_p_void_p_p__GError__void(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_f_p_f_p_void__p_void_p_void_unsigned_long_int_int_enum_GThreadPriority_p_void_p_p__GError__void() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_f_p_f_p_void__p_void_p_void_unsigned_long_int_int_enum_GThreadPriority_p_void_p_p__GError__void obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

