/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package yd.swig;

public class SWIGTYPE_p_f_p__GVfs_p_q_const__char_unsigned_long_p__GFileAttributeMatcher_p__GFileInfo_p__GCancellable_p_p_void_p_p_f_p_void__void__void {
  private transient long swigCPtr;

  protected SWIGTYPE_p_f_p__GVfs_p_q_const__char_unsigned_long_p__GFileAttributeMatcher_p__GFileInfo_p__GCancellable_p_p_void_p_p_f_p_void__void__void(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_f_p__GVfs_p_q_const__char_unsigned_long_p__GFileAttributeMatcher_p__GFileInfo_p__GCancellable_p_p_void_p_p_f_p_void__void__void() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_f_p__GVfs_p_q_const__char_unsigned_long_p__GFileAttributeMatcher_p__GFileInfo_p__GCancellable_p_p_void_p_p_f_p_void__void__void obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

